/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package OdontoSysPantallaAuxiliares;

import OdontoSysModelo.DetalleHallazgo;
import OdontoSysModelo.Diente;
import OdontoSysModelo.Hallazgo;
import OdontoSysModelo.Odontograma;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author Tito
 */
public class InsertarHallazgo extends javax.swing.JDialog {

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static DetalleHallazgo elDetalleHallazgo = null;
    public static Diente elDiente = null;
    public static Hallazgo elHallazgo = null;
    //public static Odontograma elOdontograma = null;
    
    public InsertarHallazgo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        initComponents();
        this.setLocationRelativeTo(null);
        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                doClose(elDetalleHallazgo);
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public DetalleHallazgo getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        labelHallazgoNombre = new java.awt.Label();
        labelHallazgoSimbolo = new java.awt.Label();
        jButtonBuscarHallazgo = new javax.swing.JButton();
        labelDiente = new java.awt.Label();
        labelDienteNom = new java.awt.Label();
        jButtonBuscarDiente = new javax.swing.JButton();
        jTextFieldEspecificacion = new javax.swing.JTextField();
        labelSigla = new java.awt.Label();
        jTextFieldUbicacion = new javax.swing.JTextField();
        labelUbicacion = new java.awt.Label();
        label1 = new java.awt.Label();

        setTitle("InsertarHallazgo");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        okButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        okButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/ingresar.png"))); // NOI18N
        okButton.setText("Aceptar");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/eliminar.png"))); // NOI18N
        cancelButton.setText("Cancelar");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        labelHallazgoNombre.setAlignment(java.awt.Label.CENTER);
        labelHallazgoNombre.setBackground(new java.awt.Color(204, 204, 204));
        labelHallazgoNombre.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        labelHallazgoNombre.setPreferredSize(new java.awt.Dimension(234, 20));
        labelHallazgoNombre.setText("Hallazgo");

        labelHallazgoSimbolo.setAlignment(java.awt.Label.CENTER);
        labelHallazgoSimbolo.setBackground(new java.awt.Color(204, 204, 204));
        labelHallazgoSimbolo.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        labelHallazgoSimbolo.setPreferredSize(new java.awt.Dimension(84, 20));
        labelHallazgoSimbolo.setText("Simbolo");

        jButtonBuscarHallazgo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/buscar.png"))); // NOI18N
        jButtonBuscarHallazgo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarHallazgoActionPerformed(evt);
            }
        });

        labelDiente.setAlignment(java.awt.Label.CENTER);
        labelDiente.setBackground(new java.awt.Color(204, 204, 204));
        labelDiente.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        labelDiente.setPreferredSize(new java.awt.Dimension(234, 20));
        labelDiente.setText("Diente");

        labelDienteNom.setAlignment(java.awt.Label.CENTER);
        labelDienteNom.setBackground(new java.awt.Color(204, 204, 204));
        labelDienteNom.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        labelDienteNom.setText("Nomenclatura");

        jButtonBuscarDiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/buscar.png"))); // NOI18N
        jButtonBuscarDiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarDienteActionPerformed(evt);
            }
        });

        labelSigla.setAlignment(java.awt.Label.CENTER);
        labelSigla.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        labelSigla.setText("Especificación");

        labelUbicacion.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        labelUbicacion.setText("Ubicacion");

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(new java.awt.Color(102, 102, 255));
        label1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label1.setText("Imagen");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButtonBuscarHallazgo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonBuscarDiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelUbicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(labelSigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelHallazgoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                                    .addComponent(labelDiente, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelDienteNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelHallazgoSimbolo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jTextFieldEspecificacion)
                            .addComponent(jTextFieldUbicacion)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelButton)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonBuscarHallazgo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(labelHallazgoSimbolo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                        .addComponent(labelHallazgoNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonBuscarDiente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(labelDiente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelDienteNom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelSigla, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextFieldEspecificacion, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap())
        );

        getRootPane().setDefaultButton(okButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        if(elDiente != null && elHallazgo != null){         //elOdontograma != null && 
            elDetalleHallazgo = new DetalleHallazgo();
            String Especificacion = jTextFieldEspecificacion.getText();
            String Ubicacion = jTextFieldUbicacion.getText();            
            
            elDetalleHallazgo.setOdontograma(null);
            elDetalleHallazgo.setDiente(elDiente);
            elDetalleHallazgo.setHallazgo(elHallazgo);
            elDetalleHallazgo.setEspecificacion(Especificacion);
            elDetalleHallazgo.setUbicacion(Ubicacion);
            doClose(elDetalleHallazgo);
            
        }else if(elDiente != null && elHallazgo != null){
            
            elDetalleHallazgo = new DetalleHallazgo();
            String aux = jTextFieldEspecificacion.getText();
            String Especificacion = null;
            if(aux.length()>=1 && aux.length()<=4){
                Especificacion = jTextFieldEspecificacion.getText();
            }
            
            String Ubicacion = jTextFieldUbicacion.getText();          
            
            elDetalleHallazgo.setDiente(elDiente);
            elDetalleHallazgo.setHallazgo(elHallazgo);
            elDetalleHallazgo.setEspecificacion(Especificacion);
            elDetalleHallazgo.setUbicacion(Ubicacion);
            doClose(elDetalleHallazgo);
            
        }else{
        
            
            doClose(elDetalleHallazgo);
        }   
           
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(null);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(elDetalleHallazgo);
    }//GEN-LAST:event_closeDialog

    private void jButtonBuscarHallazgoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarHallazgoActionPerformed
        // TODO add your handling code here:
      BuscarHallazgo fmrBuscador = new BuscarHallazgo(null, true);
      fmrBuscador.setVisible(rootPaneCheckingEnabled);
      elHallazgo = null;  
      elHallazgo = fmrBuscador.getReturnStatus();
      
      if(elHallazgo!=null){
          labelHallazgoNombre.setText(elHallazgo.getNombre());
          labelHallazgoSimbolo.setText(elHallazgo.getSimbolol());          
      }
      
      
    }//GEN-LAST:event_jButtonBuscarHallazgoActionPerformed

    private void jButtonBuscarDienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarDienteActionPerformed
        // TODO add your handling code here:
        BuscarDiente BuscarDiente = new BuscarDiente(null, true);
        BuscarDiente.setVisible(rootPaneCheckingEnabled);
        elDiente = null;
        elDiente = BuscarDiente.getReturnStatus();
        
        if(elDiente != null){
            labelDiente.setText(elDiente.getNombre());
            labelDienteNom.setText(String.valueOf(elDiente.getNomenclatura()));
        }
    }//GEN-LAST:event_jButtonBuscarDienteActionPerformed
    
    private void doClose(DetalleHallazgo retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertarHallazgo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertarHallazgo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertarHallazgo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertarHallazgo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                InsertarHallazgo dialog = new InsertarHallazgo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton jButtonBuscarDiente;
    private javax.swing.JButton jButtonBuscarHallazgo;
    private javax.swing.JTextField jTextFieldEspecificacion;
    private javax.swing.JTextField jTextFieldUbicacion;
    private java.awt.Label label1;
    private java.awt.Label labelDiente;
    private java.awt.Label labelDienteNom;
    private java.awt.Label labelHallazgoNombre;
    private java.awt.Label labelHallazgoSimbolo;
    private java.awt.Label labelSigla;
    private java.awt.Label labelUbicacion;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables

    private DetalleHallazgo returnStatus = null;
}
