/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package OdontoSysPantalla;

import OdontoSysControlador.DiagnosticoControlador;
import OdontoSysControlador.DoctorControlador;
import OdontoSysControlador.PacienteControlador;
import OdontoSysModelo.Diagnostico;
import OdontoSysModelo.Odontograma;
import OdontoSysModelo.Paciente;
import OdontoSysModelo.Usuario;
import OdontoSysVista.DiagnosticoVista;
import java.awt.TextField;
import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Diagnosticos extends javax.swing.JFrame {

    public Diagnosticos() {
        initComponents();
        
        jTextFieldResumenHallazgos.setLineWrap(true);
        jTextFieldResumenHallazgos.setWrapStyleWord(true);
        jTextFieldPlanTratamiento.setLineWrap(true);
        jTextFieldPlanTratamiento.setWrapStyleWord(true);
        jTextFieldObservaciones.setLineWrap(true);
        jTextFieldObservaciones.setWrapStyleWord(true);
        
        if(idDiagnostico == 0){     //Llamada a insertar
            actual = PacienteControlador.BuscarID(idPaciente);                      //Obtiene el paciente actual
            jLabelPaciente.setText(actual.getNombres() + " " + actual.getApellidos());
            habilitarTodo();
            jButtonModificar.setVisible(false);
            jLabel7.setVisible(false);
            jTextFieldEmpresa.setVisible(false);
        }else{                      //Llamada a ver y/o modificar
            jButtonGuardar.setVisible(false);
            jButtonIngresarOdontograma.setVisible(false);
            recuperarDiagnostico();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelPaciente = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDateChooserFecha = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldEmpresa = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldOdontograma = new javax.swing.JTextField();
        jButtonIngresarOdontograma = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextFieldResumenHallazgos = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextFieldPlanTratamiento = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextFieldObservaciones = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel1.setText("Diagnóstico");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Paciente");

        jLabelPaciente.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Fecha del Diagnóstico");

        jDateChooserFecha.setEnabled(false);
        jDateChooserFecha.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("Resumen de Hallazgos");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setText("Plan de Tratamiento");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setText("Observaciones");

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setText("Empresa");

        jTextFieldEmpresa.setEditable(false);
        jTextFieldEmpresa.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jButtonCancelar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/eliminar.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonGuardar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButtonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/guardar.png"))); // NOI18N
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonModificar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButtonModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/modificar.png"))); // NOI18N
        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel8.setText("Tipo");

        jComboBoxTipo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Interno", "Externo" }));
        jComboBoxTipo.setEnabled(false);
        jComboBoxTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTipoItemStateChanged(evt);
            }
        });
        jComboBoxTipo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBoxTipoFocusLost(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel9.setText("Odontograma Examen");

        jTextFieldOdontograma.setEditable(false);
        jTextFieldOdontograma.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jButtonIngresarOdontograma.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButtonIngresarOdontograma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/diente.png"))); // NOI18N
        jButtonIngresarOdontograma.setText("Ingresar Odontograma Examen");
        jButtonIngresarOdontograma.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonIngresarOdontograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarOdontogramaActionPerformed(evt);
            }
        });

        jTextFieldResumenHallazgos.setColumns(20);
        jTextFieldResumenHallazgos.setRows(4);
        jScrollPane1.setViewportView(jTextFieldResumenHallazgos);

        jTextFieldPlanTratamiento.setColumns(20);
        jTextFieldPlanTratamiento.setRows(4);
        jScrollPane2.setViewportView(jTextFieldPlanTratamiento);

        jTextFieldObservaciones.setColumns(20);
        jTextFieldObservaciones.setRows(4);
        jScrollPane3.setViewportView(jTextFieldObservaciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(22, 22, 22))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateChooserFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabelPaciente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldEmpresa, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldOdontograma, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonIngresarOdontograma))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(28, 28, 28)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabelPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jDateChooserFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(87, 87, 87)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonIngresarOdontograma)
                            .addComponent(jTextFieldOdontograma, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonGuardar)
                    .addComponent(jButtonModificar))
                .addGap(19, 19, 19))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        obtenerNuevo();
        if(nuevo != null){
            int ok = DiagnosticoVista.InsertarNuevo(nuevo);
            if(ok > 0){
                JOptionPane.showMessageDialog(rootPane, "Se insertó correctamente", "Insertar Diagnóstico", WIDTH);
                PacienteHojaClinica.pacienteActual = actual;
                PacienteHojaClinica.main(null);
                limpiar();            
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        limpiar(); 
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        habilitarTodo();
        jButtonModificar.setVisible(false);
        jButtonGuardar.setVisible(true);
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonIngresarOdontogramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarOdontogramaActionPerformed
        OdontogramaFrame.diag = 1;
        OdontogramaFrame.elPaciente = actual;
        OdontogramaFrame jFrame = new OdontogramaFrame(user);
        jFrame.setVisible(true);
        
    }//GEN-LAST:event_jButtonIngresarOdontogramaActionPerformed

    private void jComboBoxTipoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxTipoFocusLost
    }//GEN-LAST:event_jComboBoxTipoFocusLost

    private void jComboBoxTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTipoItemStateChanged
        int seleccion = jComboBoxTipo.getSelectedIndex();
        
        switch(seleccion){
            case 0:                         //Tipo Interno
                jTextFieldEmpresa.setVisible(false);
                jLabel9.setVisible(true);
                jTextFieldOdontograma.setVisible(true);
                jLabel7.setVisible(false);
                if(idDiagnostico == 0){     //Llamada a insertar
                    jButtonIngresarOdontograma.setVisible(true);                
                }else{
                    jButtonIngresarOdontograma.setVisible(false);
                }
            break;
            case 1:                          //Tipo Externo
                jTextFieldEmpresa.setVisible(true);
                jButtonIngresarOdontograma.setVisible(false);
                jLabel9.setVisible(false);
                jTextFieldOdontograma.setVisible(false);
                jLabel7.setVisible(true);
            break;
        }
        
    }//GEN-LAST:event_jComboBoxTipoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Diagnosticos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Diagnosticos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Diagnosticos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Diagnosticos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Diagnosticos().setVisible(true);
            }
        });
    }
    //Variables Globales
    public static int idDiagnostico = 0;
    public static int idPaciente;
    public static Usuario user = null;
    Diagnostico nuevo = null;
    Paciente actual = null;
    public static Odontograma odont = null;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonIngresarOdontograma;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JComboBox jComboBoxTipo;
    private com.toedter.calendar.JDateChooser jDateChooserFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelPaciente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextFieldEmpresa;
    private javax.swing.JTextArea jTextFieldObservaciones;
    public static javax.swing.JTextField jTextFieldOdontograma;
    private javax.swing.JTextArea jTextFieldPlanTratamiento;
    private javax.swing.JTextArea jTextFieldResumenHallazgos;
    // End of variables declaration//GEN-END:variables

    private void obtenerNuevo() {
        if(jDateChooserFecha.getDate() != null && jTextFieldResumenHallazgos.getText() != null && jTextFieldPlanTratamiento.getText() != null){
            nuevo = new Diagnostico();
            nuevo.setTipo(jComboBoxTipo.getSelectedItem().toString());
            nuevo.setFecha(jDateChooserFecha.getDate());
            nuevo.setEmpresa(jTextFieldEmpresa.getText());
            nuevo.setResumenHallazgos(jTextFieldResumenHallazgos.getText());
            nuevo.setPlanTratamiento(jTextFieldPlanTratamiento.getText());
            nuevo.setObservaciones(jTextFieldObservaciones.getText());
            nuevo.setDoctor(user.getDoctor());
            nuevo.setPaciente(actual);
            nuevo.setOdontograma(odont);
        }else{
            JOptionPane.showMessageDialog(null,"Favor complete todos los campos", "Validar Diagnóstico", WIDTH );
        }
        
    }

    private void limpiar() {
        jComboBoxTipo.setSelectedIndex(0);
        jTextFieldEmpresa.setText("");
        jTextFieldObservaciones.setText("");
        jTextFieldPlanTratamiento.setText("");
        jTextFieldResumenHallazgos.setText("");
        jLabelPaciente.setText("");
        jDateChooserFecha.setDate(null);
        idDiagnostico = 0;
        
    }

    private void habilitarTodo() {
        jComboBoxTipo.setEnabled(true);
        jTextFieldEmpresa.setEditable(true);
        jTextFieldObservaciones.setEditable(true);
        jTextFieldPlanTratamiento.setEditable(true);
        jTextFieldResumenHallazgos.setEditable(true);
        jDateChooserFecha.setEnabled(true);
    }

    private void recuperarDiagnostico() {
        Diagnostico actual = DiagnosticoControlador.BuscarID(idDiagnostico);
        if(actual != null){
            if(actual.getTipo().compareTo("Interno") == 0){
                jComboBoxTipo.setSelectedIndex(0);
                jLabel7.setVisible(false);
                jTextFieldEmpresa.setVisible(false);
                jTextFieldOdontograma.setText(actual.getOdontograma().getIdodontograma().toString());
            }else{
                jComboBoxTipo.setSelectedIndex(1);                
                jLabel7.setVisible(true);
                jTextFieldEmpresa.setText(actual.getEmpresa());
                jLabel9.setVisible(false);
                jTextFieldOdontograma.setVisible(false);
            }
            jLabelPaciente.setText(actual.getPaciente().getNombres() + " " + actual.getPaciente().getApellidos());
            jDateChooserFecha.setDate(actual.getFecha());
            jTextFieldResumenHallazgos.setText(actual.getResumenHallazgos());
            jTextFieldPlanTratamiento.setText(actual.getPlanTratamiento());
            jTextFieldObservaciones.setText(actual.getObservaciones());            
        }
    }
    
    static void asociarOdontograma() {
       jTextFieldOdontograma.setText(String.valueOf(odont.getIdodontograma()));
    }
}
