/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package OdontoSysPantalla;

import OdontoSysControlador.DoctorControlador;
import OdontoSysModelo.Doctor;
import OdontoSysVista.DoctorVista;
import java.text.DecimalFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import org.hibernate.Session;

/**
 *
 * @author user
 */
public class Doctores extends javax.swing.JFrame {
    /**
     * Creates new form Doctor
     */
    public Doctores() {
        initComponents();
        ocultarBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldDocCel = new javax.swing.JTextField();
        jTextFieldDocTel = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldDocDir = new javax.swing.JTextField();
        jTextFieldDocNomb = new javax.swing.JTextField();
        jTextFieldDocApe = new javax.swing.JTextField();
        jDateChooserDocFecha = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxSexo = new javax.swing.JComboBox();
        jTextFieldDocEmail = new javax.swing.JTextField();
        jTextFieldDocReg = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldDocCed = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonAtras = new javax.swing.JButton();
        jTextFieldDocCiudad = new javax.swing.JTextField();
        jButtonGuardar = new javax.swing.JButton();
        jButtonConsultarDoctor = new javax.swing.JButton();
        jButtonEliminarDoctor = new javax.swing.JButton();
        jButtonModificarDoctor = new javax.swing.JButton();
        jButtonInsertarDoctor = new javax.swing.JButton();
        jButtonMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextFieldDocCel.setEditable(false);
        jTextFieldDocCel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                soloNumerosKeyTyped(evt);
            }
        });

        jTextFieldDocTel.setEditable(false);
        jTextFieldDocTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                soloNumerosKeyTyped(evt);
            }
        });

        jLabel10.setText("Email");

        jLabel6.setText("Teléfono");

        jTextFieldDocDir.setEditable(false);

        jTextFieldDocNomb.setEditable(false);

        jTextFieldDocApe.setEditable(false);
        jTextFieldDocApe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDocApeKeyTyped(evt);
                soloLetrasKeyTyped(evt);
            }
        });

        jDateChooserDocFecha.setEnabled(false);

        jLabel9.setText("Ciudad");

        jLabel7.setText("Celular");

        jLabel3.setText("Nro de CI");

        jLabel1.setText("Nombres");

        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "M", "F" }));
        jComboBoxSexo.setEnabled(false);

        jTextFieldDocEmail.setEditable(false);
        jTextFieldDocEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDocEmailActionPerformed(evt);
            }
        });

        jTextFieldDocReg.setEditable(false);

        jLabel11.setText("Reg. Prof. Nro");

        jLabel4.setText("Fecha de Nacimiento");

        jTextFieldDocCed.setEditable(false);
        jTextFieldDocCed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                soloNumerosKeyTyped(evt);
            }
        });

        jLabel5.setText("Sexo");

        jLabel8.setText("Dirección");

        jLabel2.setText("Apellidos");

        jButtonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/eliminar.png"))); // NOI18N
        jButtonAtras.setText("Atrás");
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });

        jTextFieldDocCiudad.setEditable(false);

        jButtonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/guardar.png"))); // NOI18N
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonConsultarDoctor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/buscar.png"))); // NOI18N
        jButtonConsultarDoctor.setText("Buscar Doctor");
        jButtonConsultarDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarDoctorActionPerformed(evt);
            }
        });

        jButtonEliminarDoctor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/eliminar.png"))); // NOI18N
        jButtonEliminarDoctor.setText("Eliminar Doctor");
        jButtonEliminarDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarDoctorActionPerformed(evt);
            }
        });

        jButtonModificarDoctor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/modificar.png"))); // NOI18N
        jButtonModificarDoctor.setText("Modificar Doctor");
        jButtonModificarDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarDoctorActionPerformed(evt);
            }
        });

        jButtonInsertarDoctor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/agregar.png"))); // NOI18N
        jButtonInsertarDoctor.setText("Ingresar Doctor");
        jButtonInsertarDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarDoctorActionPerformed(evt);
            }
        });

        jButtonMenu.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jButtonMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/accesos.png"))); // NOI18N
        jButtonMenu.setText("Volver a menú principal");
        jButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDocCel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDocTel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDocDir, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDocNomb, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDocApe, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jDateChooserDocFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldDocEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDocReg, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDocCed, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDocCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonGuardar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonAtras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonMenu)))
                .addGap(50, 50, 50))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jButtonConsultarDoctor)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonInsertarDoctor)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButtonModificarDoctor)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButtonEliminarDoctor)
                    .addGap(20, 20, 20)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldDocNomb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldDocApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldDocCed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDateChooserDocFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldDocTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldDocCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldDocDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldDocCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGuardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldDocEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextFieldDocReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(jButtonMenu))
                    .addComponent(jButtonAtras))
                .addGap(20, 20, 20))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonConsultarDoctor)
                        .addComponent(jButtonEliminarDoctor)
                        .addComponent(jButtonModificarDoctor)
                        .addComponent(jButtonInsertarDoctor))
                    .addContainerGap(385, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDocEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDocEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDocEmailActionPerformed

    private void jButtonConsultarDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarDoctorActionPerformed
        limpiar();
        String cedulaString = JOptionPane.showInputDialog ( null, "Ingrese Ci de Doctor" , "Consultar Doctor" , JOptionPane.QUESTION_MESSAGE ) ;
       // int  cedula= Integer.parseInt(cedulaString);
        doctorActual = DoctorControlador.BuscarCedula(cedulaString);            
        if (doctorActual != null) {
            escribirDoctor(doctorActual);
            mostrarBotones();
        } else {
            
            //insertar un jDialog que indique que ingrese un numero de cedula
            JOptionPane.showMessageDialog(null, "Doctor no encontrado!" , "DoctorControlador" , JOptionPane.QUESTION_MESSAGE );

    }
    }//GEN-LAST:event_jButtonConsultarDoctorActionPerformed

    private void jButtonInsertarDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarDoctorActionPerformed
        limpiar();
        habilitarDatos();
        jTextFieldDocNomb.requestFocus(rootPaneCheckingEnabled);
        habilitarBotonInsertar();  
    }//GEN-LAST:event_jButtonInsertarDoctorActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
    String nombreBoton = jButtonGuardar.getText();
    obtenerDoctor();
    int valido = DoctorVista.validarDoctor(doctorActual);
    if(valido == 0){
        if(nombreBoton.compareTo("Guardar") == 0){
            int r = DoctorControlador.BuscarRegistro(doctorActual.getRegProf());
            if(r == 1){
                insertarDoctor();   
            }else{
                JOptionPane.showMessageDialog(null, "El Registro Profesional ya existe, no se puede insertar" , "Validación de Doctor" , WIDTH);
            }
        }else if(nombreBoton.compareTo("Modificar") == 0){
            modificarDoctor();     
            }
        limpiar();
        BotonesInvisibles();
    }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonModificarDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarDoctorActionPerformed
        habilitarBotonModificar();
        habilitarDatos();
    }//GEN-LAST:event_jButtonModificarDoctorActionPerformed

    private void jButtonEliminarDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarDoctorActionPerformed
        int eliminar = JOptionPane.showConfirmDialog(null, "Eliminar Doctor "+doctorActual.getNombre()+" con Ci Nro "+doctorActual.getNroCi()+"??");
        if (eliminar == JOptionPane.YES_OPTION){
             int i = DoctorControlador.Eliminar(doctorActual);
             if(i > 0 ){
                JOptionPane.showMessageDialog(rootPane, "Se eliminó correctamente", "Eliminar Doctor", WIDTH);
                limpiar();
            }else{
                JOptionPane.showMessageDialog(rootPane, "No se pudo eliminar doctor", "Eliminar Doctor", WIDTH);
            }
        }
        else{
            limpiar();
        }

    }//GEN-LAST:event_jButtonEliminarDoctorActionPerformed

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        limpiar();
        ocultarBotones();
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    private void jButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuActionPerformed
        this.setVisible(false);//oculta el jFrame actual
    }//GEN-LAST:event_jButtonMenuActionPerformed

    private void soloLetrasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_soloLetrasKeyTyped
        char c = evt.getKeyChar();
        int i = c;
        if((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (i != 8 && i != 9 && i != 13) ){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Este campo sólo admite letas A-Z o a-z", "Validez de Campo", WIDTH);
        }
    }//GEN-LAST:event_soloLetrasKeyTyped

    private void jTextFieldDocApeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDocApeKeyTyped
    }//GEN-LAST:event_jTextFieldDocApeKeyTyped

    private void soloNumerosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_soloNumerosKeyTyped
        char c = evt.getKeyChar();
        int i = c;
        if( (c < '0' || c > '9') && (i != 8 && i != 9 && i != 13) ){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Este campo sólo admite numeros", "Validez de Campo", WIDTH);
        }
    }//GEN-LAST:event_soloNumerosKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new Doctores().setVisible(true);
            }
        });

    }
    
    //Variables Globales
    Doctor doctorActual = null;
    Session sessionGlobal = null;
    DecimalFormat formateador = new DecimalFormat("###,###");
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonConsultarDoctor;
    private javax.swing.JButton jButtonEliminarDoctor;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonInsertarDoctor;
    private javax.swing.JButton jButtonMenu;
    private javax.swing.JButton jButtonModificarDoctor;
    private javax.swing.JComboBox jComboBoxSexo;
    private com.toedter.calendar.JDateChooser jDateChooserDocFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldDocApe;
    private javax.swing.JTextField jTextFieldDocCed;
    private javax.swing.JTextField jTextFieldDocCel;
    private javax.swing.JTextField jTextFieldDocCiudad;
    private javax.swing.JTextField jTextFieldDocDir;
    private javax.swing.JTextField jTextFieldDocEmail;
    private javax.swing.JTextField jTextFieldDocNomb;
    private javax.swing.JTextField jTextFieldDocReg;
    private javax.swing.JTextField jTextFieldDocTel;
    // End of variables declaration//GEN-END:variables

    private void limpiar() {
        jTextFieldDocNomb.setText("");
        jTextFieldDocApe.setText("");
        jTextFieldDocCed.setText("");
        jDateChooserDocFecha.setDate(null);
        jComboBoxSexo.setSelectedIndex(0);
        jTextFieldDocTel.setText("");
        jTextFieldDocCel.setText("");
        jTextFieldDocDir.setText("");
        jTextFieldDocCiudad.setText("");
        jTextFieldDocEmail.setText("");
        jTextFieldDocReg.setText("");
    }

    private void escribirDoctor(Doctor doctor) {
        if(doctor != null){    
            jTextFieldDocNomb.setText(doctor.getNombre());
            jTextFieldDocApe.setText(doctor.getApellido());
            jTextFieldDocCed.setText(String.valueOf(formateador.format(doctor.getNroCi())));
            jDateChooserDocFecha.setDate(doctor.getFechaNac());
            if(doctor.getSexo().compareTo("M") == 0){
                jComboBoxSexo.setSelectedIndex(0);
            }else{
                jComboBoxSexo.setSelectedIndex(1);
            }
            jTextFieldDocTel.setText(doctor.getTeLb());
            jTextFieldDocCel.setText(doctor.getTelCel());
            jTextFieldDocDir.setText(doctor.getDireccion());
            jTextFieldDocCiudad.setText(doctor.getCiudad());
            jTextFieldDocEmail.setText(doctor.getEmail());
            jTextFieldDocReg.setText(doctor.getRegProf());
        }else{
            JOptionPane.showMessageDialog(rootPane, "Doctor no encontrado", "Aviso", WIDTH);
        }  
    }
    
    private void habilitarDatos() {
        jTextFieldDocNomb.setEditable(true);
        jTextFieldDocApe.setEditable(true);
        jTextFieldDocCed.setEditable(true);
        jDateChooserDocFecha.setEnabled(true);
        jComboBoxSexo.setEnabled(true);
        jTextFieldDocTel.setEditable(true);
        jTextFieldDocCel.setEditable(true);
        jTextFieldDocDir.setEditable(true);
        jTextFieldDocCiudad.setEditable(true);
        jTextFieldDocEmail.setEditable(true);
        jTextFieldDocReg.setEditable(true);
    }

    private void habilitarBotonModificar() {
        jButtonGuardar.setVisible(true);
        jButtonGuardar.setText("Modificar");        
        jButtonAtras.setVisible(true);
        jButtonAtras.setText("Atras");    
    }

    private void habilitarBotonInsertar() {
        jButtonGuardar.setVisible(true);
        jButtonGuardar.setText("Guardar");
        jButtonAtras.setVisible(true);
        jButtonAtras.setText("Volver");
    }

    private void insertarDoctor() {
    int i = DoctorControlador.insertarDoctor(doctorActual);
    if(i > 0){
            //registro insertado correctamente
        JOptionPane.showMessageDialog(rootPane, "Registro "+i+" insertado", "Insertar Doctor", WIDTH);
        }else{
            //no insertado
        JOptionPane.showMessageDialog(rootPane, "No se pudo Insertar Doctor", "Insertar Doctor", WIDTH);      
        }    
    }

    private void modificarDoctor() {
        int i = DoctorControlador.UpDateDoctor(doctorActual);
            JOptionPane.showMessageDialog(rootPane, "Se modificó correctamente", "Modificar Doctor", WIDTH);
            doctorActual = null;
    }

    private void obtenerDoctor() {
        if(jButtonGuardar.getText().compareTo("Guardar") == 0){
            doctorActual  = new Doctor();
        }
        doctorActual.setNombre(jTextFieldDocNomb.getText());
        doctorActual.setApellido(jTextFieldDocApe.getText());
        doctorActual.setNroCi(Integer.parseInt(jTextFieldDocCed.getText().replace(".", "")));
        Date fechaNac = jDateChooserDocFecha.getDate();             
        doctorActual.setFechaNac(fechaNac);
        doctorActual.setSexo(jComboBoxSexo.getSelectedItem().toString());
        doctorActual.setTeLb(jTextFieldDocTel.getText());
        doctorActual.setTelCel(jTextFieldDocCel.getText());
        doctorActual.setDireccion(jTextFieldDocDir.getText());
        doctorActual.setCiudad(jTextFieldDocCiudad.getText());
        doctorActual.setEmail(jTextFieldDocEmail.getText());
        doctorActual.setRegProf(jTextFieldDocReg.getText());
        doctorActual.setEstado("Activo");
        
    }

    private void BotonesInvisibles() {
        jButtonGuardar.setVisible(false);
        jButtonAtras.setVisible(false);   
    }

    private void ocultarBotones() {
        jButtonModificarDoctor.setVisible(false);
        jButtonEliminarDoctor.setVisible(false);
        jButtonGuardar.setVisible(false);
        jButtonAtras.setVisible(false);
        jButtonConsultarDoctor.setVisible(true);
        jButtonInsertarDoctor.setVisible(true);
    }

    private void mostrarBotones() {
        jButtonModificarDoctor.setVisible(true);
        jButtonEliminarDoctor.setVisible(true);
        jButtonAtras.setVisible(true);
        jButtonInsertarDoctor.setVisible(false);
        jButtonConsultarDoctor.setVisible(false);
    }  

    

}
