/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package OdontoSysPantalla;

import OdontoSysControlador.DetalleHallazgoControlador;
import OdontoSysControlador.DienteControlador;
import OdontoSysControlador.DoctorControlador;
import OdontoSysControlador.OdontogramaControlador;
import OdontoSysControlador.TratamientoControlador;
import OdontoSysModelo.Odontograma;
import OdontoSysModelo.DetalleHallazgo;
import OdontoSysModelo.Diente;
import OdontoSysModelo.Paciente;
import OdontoSysModelo.Doctor;
import OdontoSysModelo.Hallazgo;
import OdontoSysModelo.Tratamiento;
import OdontoSysModelo.Usuario;
import OdontoSysPantalla.Inicio;
import OdontoSysPantallaAuxiliares.InsertarHallazgoAct;
import OdontoSysPantallaAuxiliares.InsertarTratamientoAct;
import OdontoSysPantallaAuxiliares.ObtenerPaciente;
import OdontoSysPantallaAuxiliares.OrdenDeServicio;
import OdontoSysUtil.Configuraciones;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class OdontogramaFrame extends javax.swing.JFrame {
    
    
    public OdontogramaFrame(Usuario usuario){
        initComponents(); 
        columName(); 
        jButtonEliminar.setVisible(false);
        
        if(odon == null){ 
            elUsuario = usuario;
            elDoctor = elUsuario.getDoctor();
            
   //         if(diag == 0){                          //Llamado desde el inicio
   //              seleccionTipoOdontograma();
   //         }else{          //Llamado desde frame Diagnóstico, para insertar un Examen
                mostrarDoctorPaciente();        
                jButtonSelectTratamiento.doClick();
   //         }
        }else{                          //Llamado a consultar odontograma
            elDoctor = elUsuario.getDoctor();
            
            mostrarDoctorPaciente();
            setearModelo();
            llenarTabla();
        }
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelDatosOdontograma = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldelDoctor = new javax.swing.JTextField();
        jLabelElPaciente = new javax.swing.JLabel();
        jTextFieldelPaciente = new javax.swing.JTextField();
        jButtonBuscarPaciente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonSelectHallazgo = new javax.swing.JButton();
        jButtonSelectTratamiento = new javax.swing.JButton();
        jPanelBoca = new javax.swing.JPanel();
        jPanelArribaDerecha = new javax.swing.JPanel();
        jButtonD18 = new javax.swing.JButton();
        jButtonD17 = new javax.swing.JButton();
        jButtonD16 = new javax.swing.JButton();
        jButtonD15 = new javax.swing.JButton();
        jButtonD14 = new javax.swing.JButton();
        jButtonD13 = new javax.swing.JButton();
        jButtonD12 = new javax.swing.JButton();
        jButtonD11 = new javax.swing.JButton();
        jPanelAbajoDerecha = new javax.swing.JPanel();
        jButtonD48 = new javax.swing.JButton();
        jButtonD47 = new javax.swing.JButton();
        jButtonD46 = new javax.swing.JButton();
        jButtonD45 = new javax.swing.JButton();
        jButtonD44 = new javax.swing.JButton();
        jButtonD43 = new javax.swing.JButton();
        jButtonD42 = new javax.swing.JButton();
        jButtonD41 = new javax.swing.JButton();
        jPanelArribaIzquierda = new javax.swing.JPanel();
        jButtonD21 = new javax.swing.JButton();
        jButtonD22 = new javax.swing.JButton();
        jButtonD23 = new javax.swing.JButton();
        jButtonD24 = new javax.swing.JButton();
        jButtonD25 = new javax.swing.JButton();
        jButtonD26 = new javax.swing.JButton();
        jButtonD27 = new javax.swing.JButton();
        jButtonD28 = new javax.swing.JButton();
        jPanelAbajoIzquierda = new javax.swing.JPanel();
        jButtonD31 = new javax.swing.JButton();
        jButtonD32 = new javax.swing.JButton();
        jButtonD33 = new javax.swing.JButton();
        jButtonD34 = new javax.swing.JButton();
        jButtonD35 = new javax.swing.JButton();
        jButtonD36 = new javax.swing.JButton();
        jButtonD37 = new javax.swing.JButton();
        jButtonD38 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableContenedorDatos = new javax.swing.JTable();
        jButtonGuardarOdonto = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jPanelDatosOdontograma.setBackground(new java.awt.Color(204, 204, 204));
        jPanelDatosOdontograma.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel1.setText("Doctor");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextFieldelDoctor.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTextFieldelDoctor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextFieldelDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldelDoctorActionPerformed(evt);
            }
        });

        jLabelElPaciente.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabelElPaciente.setText("Paciente");
        jLabelElPaciente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextFieldelPaciente.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTextFieldelPaciente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonBuscarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/agregar.png"))); // NOI18N
        jButtonBuscarPaciente.setEnabled(false);
        jButtonBuscarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarPacienteActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel2.setText("Tipo");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonSelectHallazgo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButtonSelectHallazgo.setText("Halllazgo");
        jButtonSelectHallazgo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectHallazgoActionPerformed(evt);
            }
        });

        jButtonSelectTratamiento.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButtonSelectTratamiento.setText("Tratamiento");
        jButtonSelectTratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectTratamientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDatosOdontogramaLayout = new javax.swing.GroupLayout(jPanelDatosOdontograma);
        jPanelDatosOdontograma.setLayout(jPanelDatosOdontogramaLayout);
        jPanelDatosOdontogramaLayout.setHorizontalGroup(
            jPanelDatosOdontogramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosOdontogramaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosOdontogramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelElPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosOdontogramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosOdontogramaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonSelectHallazgo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSelectTratamiento))
                    .addComponent(jTextFieldelDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldelPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelDatosOdontogramaLayout.setVerticalGroup(
            jPanelDatosOdontogramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosOdontogramaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosOdontogramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldelDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosOdontogramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelDatosOdontogramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelElPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldelPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosOdontogramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSelectHallazgo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSelectTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelBoca.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBoca.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanelArribaDerecha.setBackground(new java.awt.Color(153, 153, 255));
        jPanelArribaDerecha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonD18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/18.jpg"))); // NOI18N
        jButtonD18.setIconTextGap(1);
        jButtonD18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonD18ActionPerformed(evt);
            }
        });

        jButtonD17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/17.jpg"))); // NOI18N
        jButtonD17.setIconTextGap(1);
        jButtonD17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonD17ActionPerformed(evt);
            }
        });

        jButtonD16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/16.jpg"))); // NOI18N
        jButtonD16.setIconTextGap(1);
        jButtonD16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonD16ActionPerformed(evt);
            }
        });

        jButtonD15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/15.jpg"))); // NOI18N
        jButtonD15.setIconTextGap(1);
        jButtonD15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonD15ActionPerformed(evt);
            }
        });

        jButtonD14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/14.jpg"))); // NOI18N
        jButtonD14.setIconTextGap(1);
        jButtonD14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonD14ActionPerformed(evt);
            }
        });

        jButtonD13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/13.jpg"))); // NOI18N
        jButtonD13.setIconTextGap(1);
        jButtonD13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonD13ActionPerformed(evt);
            }
        });

        jButtonD12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/12.jpg"))); // NOI18N
        jButtonD12.setIconTextGap(1);
        jButtonD12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonD12ActionPerformed(evt);
            }
        });

        jButtonD11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/11.jpg"))); // NOI18N
        jButtonD11.setIconTextGap(1);
        jButtonD11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonD11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelArribaDerechaLayout = new javax.swing.GroupLayout(jPanelArribaDerecha);
        jPanelArribaDerecha.setLayout(jPanelArribaDerechaLayout);
        jPanelArribaDerechaLayout.setHorizontalGroup(
            jPanelArribaDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelArribaDerechaLayout.createSequentialGroup()
                .addComponent(jButtonD18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jButtonD17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButtonD16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButtonD15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jButtonD14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButtonD13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jButtonD12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButtonD11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelArribaDerechaLayout.setVerticalGroup(
            jPanelArribaDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonD17, javax.swing.GroupLayout.PREFERRED_SIZE, 82, Short.MAX_VALUE)
            .addComponent(jButtonD18, javax.swing.GroupLayout.PREFERRED_SIZE, 82, Short.MAX_VALUE)
            .addComponent(jButtonD16, javax.swing.GroupLayout.PREFERRED_SIZE, 82, Short.MAX_VALUE)
            .addComponent(jButtonD13, javax.swing.GroupLayout.PREFERRED_SIZE, 82, Short.MAX_VALUE)
            .addComponent(jButtonD15, javax.swing.GroupLayout.PREFERRED_SIZE, 82, Short.MAX_VALUE)
            .addComponent(jButtonD14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, Short.MAX_VALUE)
            .addComponent(jButtonD12, javax.swing.GroupLayout.PREFERRED_SIZE, 82, Short.MAX_VALUE)
            .addComponent(jButtonD11, javax.swing.GroupLayout.PREFERRED_SIZE, 82, Short.MAX_VALUE)
        );

        jPanelAbajoDerecha.setBackground(new java.awt.Color(153, 153, 255));
        jPanelAbajoDerecha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonD48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/48.jpg"))); // NOI18N
        jButtonD48.setIconTextGap(1);
        jButtonD48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonD48ActionPerformed(evt);
            }
        });

        jButtonD47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/47.jpg"))); // NOI18N
        jButtonD47.setIconTextGap(1);
        jButtonD47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonD47ActionPerformed(evt);
            }
        });

        jButtonD46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/46.jpg"))); // NOI18N
        jButtonD46.setIconTextGap(1);
        jButtonD46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonD46ActionPerformed(evt);
            }
        });

        jButtonD45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/45.jpg"))); // NOI18N
        jButtonD45.setIconTextGap(1);
        jButtonD45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonD45ActionPerformed(evt);
            }
        });

        jButtonD44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/44.jpg"))); // NOI18N
        jButtonD44.setIconTextGap(1);
        jButtonD44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonD44ActionPerformed(evt);
            }
        });

        jButtonD43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/43.jpg"))); // NOI18N
        jButtonD43.setIconTextGap(1);
        jButtonD43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonD43ActionPerformed(evt);
            }
        });

        jButtonD42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/42.jpg"))); // NOI18N
        jButtonD42.setIconTextGap(1);
        jButtonD42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonD42ActionPerformed(evt);
            }
        });

        jButtonD41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/41.jpg"))); // NOI18N
        jButtonD41.setIconTextGap(1);
        jButtonD41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonD41ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAbajoDerechaLayout = new javax.swing.GroupLayout(jPanelAbajoDerecha);
        jPanelAbajoDerecha.setLayout(jPanelAbajoDerechaLayout);
        jPanelAbajoDerechaLayout.setHorizontalGroup(
            jPanelAbajoDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAbajoDerechaLayout.createSequentialGroup()
                .addComponent(jButtonD48, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jButtonD47, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButtonD46, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButtonD45, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jButtonD44, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButtonD43, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jButtonD42, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButtonD41, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelAbajoDerechaLayout.setVerticalGroup(
            jPanelAbajoDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonD47, javax.swing.GroupLayout.PREFERRED_SIZE, 82, Short.MAX_VALUE)
            .addComponent(jButtonD48, javax.swing.GroupLayout.PREFERRED_SIZE, 82, Short.MAX_VALUE)
            .addComponent(jButtonD46, javax.swing.GroupLayout.PREFERRED_SIZE, 82, Short.MAX_VALUE)
            .addComponent(jButtonD43, javax.swing.GroupLayout.PREFERRED_SIZE, 82, Short.MAX_VALUE)
            .addComponent(jButtonD45, javax.swing.GroupLayout.PREFERRED_SIZE, 82, Short.MAX_VALUE)
            .addComponent(jButtonD44, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, Short.MAX_VALUE)
            .addComponent(jButtonD42, javax.swing.GroupLayout.PREFERRED_SIZE, 82, Short.MAX_VALUE)
            .addComponent(jButtonD41, javax.swing.GroupLayout.PREFERRED_SIZE, 82, Short.MAX_VALUE)
        );

        jPanelArribaIzquierda.setBackground(new java.awt.Color(153, 153, 255));
        jPanelArribaIzquierda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonD21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/21.jpg"))); // NOI18N
        jButtonD21.setIconTextGap(1);
        jButtonD21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonD21ActionPerformed(evt);
            }
        });

        jButtonD22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/22.jpg"))); // NOI18N
        jButtonD22.setIconTextGap(1);
        jButtonD22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonD22ActionPerformed(evt);
            }
        });

        jButtonD23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/23.jpg"))); // NOI18N
        jButtonD23.setIconTextGap(1);
        jButtonD23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonD23ActionPerformed(evt);
            }
        });

        jButtonD24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/24.jpg"))); // NOI18N
        jButtonD24.setIconTextGap(1);
        jButtonD24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonD24ActionPerformed(evt);
            }
        });

        jButtonD25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/25.jpg"))); // NOI18N
        jButtonD25.setIconTextGap(1);
        jButtonD25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonD25ActionPerformed(evt);
            }
        });

        jButtonD26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/26.jpg"))); // NOI18N
        jButtonD26.setIconTextGap(1);
        jButtonD26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonD26ActionPerformed(evt);
            }
        });

        jButtonD27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/27.jpg"))); // NOI18N
        jButtonD27.setIconTextGap(1);
        jButtonD27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonD27ActionPerformed(evt);
            }
        });

        jButtonD28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/28.jpg"))); // NOI18N
        jButtonD28.setIconTextGap(1);
        jButtonD28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonD28ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelArribaIzquierdaLayout = new javax.swing.GroupLayout(jPanelArribaIzquierda);
        jPanelArribaIzquierda.setLayout(jPanelArribaIzquierdaLayout);
        jPanelArribaIzquierdaLayout.setHorizontalGroup(
            jPanelArribaIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelArribaIzquierdaLayout.createSequentialGroup()
                .addComponent(jButtonD21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jButtonD22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButtonD23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButtonD24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jButtonD25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButtonD26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jButtonD27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButtonD28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelArribaIzquierdaLayout.setVerticalGroup(
            jPanelArribaIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonD22, javax.swing.GroupLayout.PREFERRED_SIZE, 82, Short.MAX_VALUE)
            .addComponent(jButtonD21, javax.swing.GroupLayout.PREFERRED_SIZE, 82, Short.MAX_VALUE)
            .addComponent(jButtonD23, javax.swing.GroupLayout.PREFERRED_SIZE, 82, Short.MAX_VALUE)
            .addComponent(jButtonD26, javax.swing.GroupLayout.PREFERRED_SIZE, 82, Short.MAX_VALUE)
            .addComponent(jButtonD24, javax.swing.GroupLayout.PREFERRED_SIZE, 82, Short.MAX_VALUE)
            .addComponent(jButtonD25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, Short.MAX_VALUE)
            .addComponent(jButtonD27, javax.swing.GroupLayout.PREFERRED_SIZE, 82, Short.MAX_VALUE)
            .addComponent(jButtonD28, javax.swing.GroupLayout.PREFERRED_SIZE, 82, Short.MAX_VALUE)
        );

        jPanelAbajoIzquierda.setBackground(new java.awt.Color(153, 153, 255));
        jPanelAbajoIzquierda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonD31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/31.jpg"))); // NOI18N
        jButtonD31.setIconTextGap(1);
        jButtonD31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonD31ActionPerformed(evt);
            }
        });

        jButtonD32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/32.jpg"))); // NOI18N
        jButtonD32.setIconTextGap(1);
        jButtonD32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonD32ActionPerformed(evt);
            }
        });

        jButtonD33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/33.jpg"))); // NOI18N
        jButtonD33.setIconTextGap(1);
        jButtonD33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonD33ActionPerformed(evt);
            }
        });

        jButtonD34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/34.jpg"))); // NOI18N
        jButtonD34.setIconTextGap(1);
        jButtonD34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonD34ActionPerformed(evt);
            }
        });

        jButtonD35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/35.jpg"))); // NOI18N
        jButtonD35.setIconTextGap(1);
        jButtonD35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonD35ActionPerformed(evt);
            }
        });

        jButtonD36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/36.jpg"))); // NOI18N
        jButtonD36.setIconTextGap(1);
        jButtonD36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonD36ActionPerformed(evt);
            }
        });

        jButtonD37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/37.jpg"))); // NOI18N
        jButtonD37.setIconTextGap(1);
        jButtonD37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonD37ActionPerformed(evt);
            }
        });

        jButtonD38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/38.jpg"))); // NOI18N
        jButtonD38.setIconTextGap(1);
        jButtonD38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonD38ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAbajoIzquierdaLayout = new javax.swing.GroupLayout(jPanelAbajoIzquierda);
        jPanelAbajoIzquierda.setLayout(jPanelAbajoIzquierdaLayout);
        jPanelAbajoIzquierdaLayout.setHorizontalGroup(
            jPanelAbajoIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAbajoIzquierdaLayout.createSequentialGroup()
                .addComponent(jButtonD31, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jButtonD32, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButtonD33, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButtonD34, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jButtonD35, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButtonD36, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jButtonD37, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButtonD38, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelAbajoIzquierdaLayout.setVerticalGroup(
            jPanelAbajoIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonD32, javax.swing.GroupLayout.PREFERRED_SIZE, 82, Short.MAX_VALUE)
            .addComponent(jButtonD31, javax.swing.GroupLayout.PREFERRED_SIZE, 82, Short.MAX_VALUE)
            .addComponent(jButtonD33, javax.swing.GroupLayout.PREFERRED_SIZE, 82, Short.MAX_VALUE)
            .addComponent(jButtonD36, javax.swing.GroupLayout.PREFERRED_SIZE, 82, Short.MAX_VALUE)
            .addComponent(jButtonD34, javax.swing.GroupLayout.PREFERRED_SIZE, 82, Short.MAX_VALUE)
            .addComponent(jButtonD35, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, Short.MAX_VALUE)
            .addComponent(jButtonD37, javax.swing.GroupLayout.PREFERRED_SIZE, 82, Short.MAX_VALUE)
            .addComponent(jButtonD38, javax.swing.GroupLayout.PREFERRED_SIZE, 82, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelBocaLayout = new javax.swing.GroupLayout(jPanelBoca);
        jPanelBoca.setLayout(jPanelBocaLayout);
        jPanelBocaLayout.setHorizontalGroup(
            jPanelBocaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBocaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBocaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBocaLayout.createSequentialGroup()
                        .addComponent(jPanelArribaDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelArribaIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBocaLayout.createSequentialGroup()
                        .addComponent(jPanelAbajoDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(jPanelAbajoIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelBocaLayout.setVerticalGroup(
            jPanelBocaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBocaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBocaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelArribaIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelArribaDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addGroup(jPanelBocaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelAbajoDerecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelAbajoIzquierda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTableContenedorDatos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTableContenedorDatos.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTableContenedorDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Diente ", "Tipo", "Nomenclatura", "Title 4"
            }
        ));
        jTableContenedorDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableContenedorDatosMouseClicked(evt);
            }
        });
        jTableContenedorDatos.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jTableContenedorDatosComponentAdded(evt);
            }
        });
        jTableContenedorDatos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTableContenedorDatosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTableContenedorDatosFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(jTableContenedorDatos);

        jButtonGuardarOdonto.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButtonGuardarOdonto.setText("GuardarOdontograma");
        jButtonGuardarOdonto.setEnabled(false);
        jButtonGuardarOdonto.setPreferredSize(new java.awt.Dimension(170, 25));
        jButtonGuardarOdonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarOdontoActionPerformed(evt);
            }
        });

        jButtonEliminar.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButtonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/borrar.png"))); // NOI18N
        jButtonEliminar.setText("Hallazgo");
        jButtonEliminar.setPreferredSize(new java.awt.Dimension(170, 25));
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jButtonVolver.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButtonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/eliminar.png"))); // NOI18N
        jButtonVolver.setText("Volver");
        jButtonVolver.setPreferredSize(new java.awt.Dimension(170, 25));
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelBoca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(jPanelDatosOdontograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGuardarOdonto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVolver, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelBoca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelDatosOdontograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonGuardarOdonto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldelDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldelDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldelDoctorActionPerformed

    private void jButtonD47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonD47ActionPerformed
        // TODO add your handling code here:
        int nomDiente = 47;
        procesarDiente(nomDiente);
    }//GEN-LAST:event_jButtonD47ActionPerformed

    private void jButtonD44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonD44ActionPerformed
        // TODO add your handling code here:
        int nomDiente = 44;
        procesarDiente(nomDiente);
    }//GEN-LAST:event_jButtonD44ActionPerformed

    private void jButtonD22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonD22ActionPerformed
        // TODO add your handling code here:
        int nomDiente = 22;
        procesarDiente(nomDiente);
    }//GEN-LAST:event_jButtonD22ActionPerformed

    private void jButtonD25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonD25ActionPerformed
        // TODO add your handling code here:
        int nomDiente = 25;
        procesarDiente(nomDiente);
    }//GEN-LAST:event_jButtonD25ActionPerformed

    private void jButtonD17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonD17ActionPerformed
        // TODO add your handling code here:
        int nomDiente = 17;
        procesarDiente(nomDiente);
    }//GEN-LAST:event_jButtonD17ActionPerformed

    private void jButtonD14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonD14ActionPerformed
        // TODO add your handling code here:
        int nomDiente = 14;
        procesarDiente(nomDiente);
    }//GEN-LAST:event_jButtonD14ActionPerformed

    private void jButtonD32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonD32ActionPerformed
        // TODO add your handling code here:
        int nomDiente = 32;
        procesarDiente(nomDiente);
    }//GEN-LAST:event_jButtonD32ActionPerformed

    private void jButtonD35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonD35ActionPerformed
        // TODO add your handling code here:
        int nomDiente = 35;
        procesarDiente(nomDiente);
    }//GEN-LAST:event_jButtonD35ActionPerformed

    private void jButtonD11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonD11ActionPerformed
        //tipoTransaction = jComboBoxTipos.getSelectedIndex();
        int nomDiente = 11;
        procesarDiente(nomDiente);
        
    }//GEN-LAST:event_jButtonD11ActionPerformed

    private void jButtonSelectHallazgoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectHallazgoActionPerformed
        // TODO add your handling code here:
        jButtonSelectTratamiento.setEnabled(false);
        jButtonEliminar.setText("Hallazgo");
        //jButtonSelectAtras.setEnabled(true);
        
        tipoTransaction = 1;
        columName();
        
        //jButtonSelectAtras.setFont(new java.awt.Font("Tahoma", 0, 12));
        jButtonSelectHallazgo.setFont(new java.awt.Font("Tahoma", 1, 12));
    }//GEN-LAST:event_jButtonSelectHallazgoActionPerformed

    private void jButtonSelectTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectTratamientoActionPerformed
        // TODO add your handling code here:
        jButtonSelectHallazgo.setEnabled(false);
        jButtonEliminar.setText("Tratamiento");
        //jButtonSelectAtras.setEnabled(true);
        
        tipoTransaction = 2;
        columName();
        
        //jButtonSelectAtras.setFont(new java.awt.Font("Tahoma", 0, 12));
        jButtonSelectTratamiento.setFont(new java.awt.Font("Tahoma", 1, 12));
    }//GEN-LAST:event_jButtonSelectTratamientoActionPerformed

    private void jButtonD12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonD12ActionPerformed
        // TODO add your handling code here:
        int nomDiente = 12;
        procesarDiente(nomDiente);
    }//GEN-LAST:event_jButtonD12ActionPerformed

    private void jButtonD13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonD13ActionPerformed
        // TODO add your handling code here:
        int nomDiente = 13;
        procesarDiente(nomDiente);
    }//GEN-LAST:event_jButtonD13ActionPerformed

    private void jButtonD15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonD15ActionPerformed
        // TODO add your handling code here:
        int nomDiente = 15;
        procesarDiente(nomDiente);
    }//GEN-LAST:event_jButtonD15ActionPerformed

    private void jButtonD16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonD16ActionPerformed
        // TODO add your handling code here:
        int nomDiente = 16;
        procesarDiente(nomDiente);
    }//GEN-LAST:event_jButtonD16ActionPerformed

    private void jButtonD18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonD18ActionPerformed
        // TODO add your handling code here:
        int nomDiente = 18;
        procesarDiente(nomDiente);
    }//GEN-LAST:event_jButtonD18ActionPerformed

    private void jButtonD21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonD21ActionPerformed
        // TODO add your handling code here:
        int nomDiente = 21;
        procesarDiente(nomDiente);
    }//GEN-LAST:event_jButtonD21ActionPerformed

    private void jButtonD23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonD23ActionPerformed
        // TODO add your handling code here:
        int nomDiente = 23;
        procesarDiente(nomDiente);
    }//GEN-LAST:event_jButtonD23ActionPerformed

    private void jButtonD24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonD24ActionPerformed
        // TODO add your handling code here:
        int nomDiente = 24;
        procesarDiente(nomDiente);
    }//GEN-LAST:event_jButtonD24ActionPerformed

    private void jButtonD26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonD26ActionPerformed
        // TODO add your handling code here:
        int nomDiente = 26;
        procesarDiente(nomDiente);
    }//GEN-LAST:event_jButtonD26ActionPerformed

    private void jButtonD27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonD27ActionPerformed
        // TODO add your handling code here:
        int nomDiente = 27;
        procesarDiente(nomDiente);
    }//GEN-LAST:event_jButtonD27ActionPerformed

    private void jButtonD28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonD28ActionPerformed
        // TODO add your handling code here:
        int nomDiente = 28;
        procesarDiente(nomDiente);
    }//GEN-LAST:event_jButtonD28ActionPerformed

    private void jButtonD41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonD41ActionPerformed
        // TODO add your handling code here:
        int nomDiente = 41;
        procesarDiente(nomDiente);
    }//GEN-LAST:event_jButtonD41ActionPerformed

    private void jButtonD42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonD42ActionPerformed
        // TODO add your handling code here:
        int nomDiente = 42;
        procesarDiente(nomDiente);
    }//GEN-LAST:event_jButtonD42ActionPerformed

    private void jButtonD43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonD43ActionPerformed
        // TODO add your handling code here:
        int nomDiente = 43;
        procesarDiente(nomDiente);
    }//GEN-LAST:event_jButtonD43ActionPerformed

    private void jButtonD45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonD45ActionPerformed
        // TODO add your handling code here:
        int nomDiente = 45;
        procesarDiente(nomDiente);
    }//GEN-LAST:event_jButtonD45ActionPerformed

    private void jButtonD46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonD46ActionPerformed
        // TODO add your handling code here:
        int nomDiente = 46;
        procesarDiente(nomDiente);
    }//GEN-LAST:event_jButtonD46ActionPerformed

    private void jButtonD48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonD48ActionPerformed
        // TODO add your handling code here:
        int nomDiente = 48;
        procesarDiente(nomDiente);
    }//GEN-LAST:event_jButtonD48ActionPerformed

    private void jButtonD31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonD31ActionPerformed
        // TODO add your handling code here:
        int nomDiente = 31;
        procesarDiente(nomDiente);
    }//GEN-LAST:event_jButtonD31ActionPerformed

    private void jButtonD33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonD33ActionPerformed
        // TODO add your handling code here:
        int nomDiente = 33;
        procesarDiente(nomDiente);
    }//GEN-LAST:event_jButtonD33ActionPerformed

    private void jButtonD34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonD34ActionPerformed
        // TODO add your handling code here:
        int nomDiente = 34;
        procesarDiente(nomDiente);
    }//GEN-LAST:event_jButtonD34ActionPerformed

    private void jButtonD36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonD36ActionPerformed
        // TODO add your handling code here:
        int nomDiente = 36;
        procesarDiente(nomDiente);
    }//GEN-LAST:event_jButtonD36ActionPerformed

    private void jButtonD37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonD37ActionPerformed
        // TODO add your handling code here:
        int nomDiente = 37;
        procesarDiente(nomDiente);
    }//GEN-LAST:event_jButtonD37ActionPerformed

    private void jButtonD38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonD38ActionPerformed
        // TODO add your handling code here:
        int nomDiente = 38;
        procesarDiente(nomDiente);
    }//GEN-LAST:event_jButtonD38ActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
        int cantRowHallazgo = modeloH.getRowCount();
        int cantRowTratamiento = modeloT.getRowCount();
        int fila;
        int cantActual = 0;
        if(tipoTransaction == 1 && cantRowHallazgo > 0){
            fila = jTableContenedorDatos.getSelectedRow();
            modeloH.removeRow(fila);
            hallazgosSet.remove(fila);
            
            cantActual = modeloH.getRowCount(); 
            jButtonEliminar.setVisible(false);
        }else if(tipoTransaction == 2 && cantRowTratamiento > 0){
            fila = jTableContenedorDatos.getSelectedRow();
            modeloT.removeRow(fila);
            listaTratamientos.remove(fila);
            
            cantActual = modeloT.getRowCount();  
            jButtonEliminar.setVisible(false);          
        }else{
            JOptionPane.showMessageDialog(null, "No hay qué Borrar", "Borra Hallazgo/Tratamiento", ERROR);
        }
        
        if(cantActual <= 0){
            jButtonEliminar.setEnabled(false);
            jButtonGuardarOdonto.setEnabled(false);
        }else{
            jButtonGuardarOdonto.setEnabled(true);
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonBuscarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarPacienteActionPerformed
        // TODO add your handling code here:
        int bandera = 0;
        while(bandera == 0){
            ObtenerPaciente frameP = new ObtenerPaciente(this, true);
            frameP.setVisible(true);
            elPaciente = frameP.getReturnStatus();
            if(elPaciente != null){
                jTextFieldelPaciente.setText(elPaciente.getNombres() + " " + elPaciente.getApellidos());
                bandera = 1;
            }else{
                this.setVisible(false);
            }
        }       
        
    }//GEN-LAST:event_jButtonBuscarPacienteActionPerformed

    private void jButtonGuardarOdontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarOdontoActionPerformed
        boolean x = false;
        Odontograma newOdont = new Odontograma();
        newOdont.setPaciente(elPaciente);
        newOdont.setDoctor(elDoctor);
        Date fecha = new Date();
        newOdont.setFecha(fecha);
        
        if(tipoTransaction == 1){
            newOdont.setTipo("Examen");
        }else{ 
            newOdont.setTipo("Tratamiento");
        }
        newOdont = OdontogramaControlador.insertarOdontograma(newOdont);
        //newOdont.setIdodontograma(idPersistencia);
        if(tipoTransaction == 1){
            Iterator<DetalleHallazgo> it = hallazgosSet.iterator();
            DetalleHallazgo h;
            while(it.hasNext()){
                h = it.next();
                h.setOdontograma(newOdont);
            }
            x = DetalleHallazgoControlador.insertarDetalleHallazgos(hallazgosSet);
            
            if(diag != 0){
            Diagnosticos.odont = newOdont;
            Diagnosticos.asociarOdontograma();
            }
             
            elPaciente = null;
            this.setVisible(false); 
            
        }else{
            Iterator<Tratamiento> it = listaTratamientos.iterator();
            Tratamiento T;
            while(it.hasNext()){
                T = it.next();
                T.setOdontograma(newOdont);
            }
            x = TratamientoControlador.insertarTratamientos(listaTratamientos);
        
               
        //LLamar a generar orden de servicio con los respectivos Tratamientos de este Odontograma
        //si es que el odontograma es de tipo tratamiento osea tipoTransaction == 2
        OrdenDeServicio.listDetalles = listaTratamientos;
        OrdenDeServicio.pacActual = elPaciente;
        OrdenDeServicio.odonActual = newOdont;
        OrdenDeServicio.user = elUsuario;
        
        OrdenDeServicio fmrOrden = new OrdenDeServicio();
        fmrOrden.setVisible(true);
        
        elPaciente = null;
        Configuraciones.limpiarModelo(modeloH);
        Configuraciones.limpiarModelo(modeloT);
        this.setVisible(false); 
       }
        
        
    }//GEN-LAST:event_jButtonGuardarOdontoActionPerformed

    private void jTableContenedorDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableContenedorDatosMouseClicked
        int fila = jTableContenedorDatos.rowAtPoint(evt.getPoint());
                if (fila > -1){
                    jButtonEliminar.setVisible(true);
                }
    }//GEN-LAST:event_jTableContenedorDatosMouseClicked

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        elPaciente = null;
        this.setVisible(false);
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jTableContenedorDatosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTableContenedorDatosFocusGained
        int fila = jTableContenedorDatos.rowAtPoint(evt.getComponent().getLocation());
         if (fila > -1){        //El foco tiene una fila
             jButtonEliminar.setVisible(true);
         }else{
             jButtonEliminar.setVisible(false);
         }
    }//GEN-LAST:event_jTableContenedorDatosFocusGained

    private void jTableContenedorDatosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTableContenedorDatosFocusLost
        jButtonEliminar.setVisible(false);
    }//GEN-LAST:event_jTableContenedorDatosFocusLost

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        jButtonEliminar.setVisible(false);
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jTableContenedorDatosComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTableContenedorDatosComponentAdded

    }//GEN-LAST:event_jTableContenedorDatosComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OdontogramaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OdontogramaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OdontogramaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OdontogramaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                OdontogramaFrame tr = new OdontogramaFrame(elUsuario);//.setVisible(true);
                tr.setVisible(true);
                //tr.seleccionTipoOdontograma();
            }
        });
    }
    
    private void columName(){
        
        if(tipoTransaction == 1){
            String row[] = new String[]{"Nombre de Hallazgo", "NombreDiente", "Nomenclatura", "Ubicacion", "Especificacion"};
            
                modeloH.setColumnIdentifiers(row);
            
            jTableContenedorDatos.setModel(modeloH);
        }else if(tipoTransaction == 2){
            String row[] = new String[]{"Descripcion de Servicio", "PrecioServicio","NombreDiente", "Nomenclatura", "Estado", "Especificacion"};
            
                modeloT.setColumnIdentifiers(row);
            
            jTableContenedorDatos.setModel(modeloT);
        }else if(tipoTransaction == 0){
            jTableContenedorDatos.setModel(new javax.swing.table.DefaultTableModel(
	        new Object[][]{
		               {null, null, null, null},
		               {null, null, null, null},
		               {null, null, null, null},
		               {null, null, null, null},
		               {null, null, null, null},
		               {null, null, null, null},
		               {null, null, null, null},
		               {null, null, null, null}
	        },
	        new String[]{
		     "Nombre Tipo Odontograma", "NombreDiente", "Nomenclatura", "Ubicacion/Estado", "Especificacion"
	        }
	));
        }
    }
    
    private String eventoSig(){
        String s;
        if(tipoTransaction == 1){
            s = "Tratamiento paciente actual";
        }else if(tipoTransaction == 2){ 
            s = "Hallazgo paciente actual";
        }else{  
            s = "no puede ocurrir";
        }
        return s;
    }
    
/*    private void seleccionTipoOdontograma(){
        Object s = JOptionPane.showInputDialog(null, "Selecione tipo de Odontograma", "Tipo de Odontograma", JOptionPane.QUESTION_MESSAGE, null, new Object[]{"Examen", "Tratamiento"}, 0);
        if(s != null){
            String tipo = s.toString();
            if(tipo.compareTo("Examen") == 0){
                if(elPaciente == null)
                    mostrarDoctorPaciente();
                    jButtonSelectHallazgo.doClick();
            }else if(tipo.compareTo("Tratamiento") == 0){
                if(elPaciente == null)
                    mostrarDoctorPaciente();            
                    jButtonSelectTratamiento.doClick();
                }
         }else{
            jButtonVolver.doClick();
                this.setVisible(false);
         }
    }*/
    
    private void cargarTablaHallago(DetalleHallazgo nuevoHallazgo) {
        String row[] = new String[5];
        row[0] = nuevoHallazgo.getHallazgo().getNombre();
        row[1] = nuevoHallazgo.getDiente().getNombre();
        row[2] = String.valueOf(nuevoHallazgo.getDiente().getNomenclatura());
        row[3] = nuevoHallazgo.getUbicacion();
        row[4] = nuevoHallazgo.getEspecificacion();
        
        modeloH.addRow(row);
        hallazgosSet.add(nuevoHallazgo);
    }
    
    private void cargarTablaTratamiento(Tratamiento nuevoTratamiento) {
        String row[] = new String[6];
        row[0] = nuevoTratamiento.getServicio().getDescripcion();
        row[1] = String.valueOf(nuevoTratamiento.getServicio().getPrecio());
        row[2] = nuevoTratamiento.getDiente().getNombre();
        row[3] = String.valueOf(nuevoTratamiento.getDiente().getNomenclatura());
        row[4] = nuevoTratamiento.getEstado();
        row[5] = nuevoTratamiento.getEspecificacion();

        modeloT.addRow(row);
        listaTratamientos.add(nuevoTratamiento);
    }
    
    private void procesarDiente(int nomDiente) {
        nuevoHallazgo = null;
        nuevoTratamiento = null;
        dienteActual = null;
        
        if(tipoTransaction == 1){
            
            dienteActual = DienteControlador.BuscarDiente(nomDiente);
            
            InsertarHallazgoAct InsertH = new InsertarHallazgoAct(this, true);
            //InsertH.GraficarDiente(String.valueOf(dienteActual.getNomenclatura()));
            InsertH.GraficarDiente(String.valueOf(nomDiente));
            InsertH.setVisible(rootPaneCheckingEnabled);
            nuevoHallazgo = InsertH.getReturnStatus();
            
            if(nuevoHallazgo != null){
                nuevoHallazgo.setDiente(dienteActual);
                cargarTablaHallago(nuevoHallazgo);
                jButtonGuardarOdonto.setEnabled(true);
            }else{
                JOptionPane.showMessageDialog(null, "No ha Generado ningun Hallazgo", "Generar Hallazgo", JOptionPane.ERROR_MESSAGE);
            }
            
        }else if(tipoTransaction == 2){
            dienteActual = DienteControlador.BuscarDiente(nomDiente);
            
            InsertarTratamientoAct InsertT = new InsertarTratamientoAct(this, true);
            InsertT.GraficarDiente(String.valueOf(nomDiente));
            InsertT.setVisible(rootPaneCheckingEnabled);
            
            nuevoTratamiento = InsertT.getReturnStatus();
            
            if(nuevoTratamiento != null){
                nuevoTratamiento.setDiente(dienteActual);
                cargarTablaTratamiento(nuevoTratamiento);
                jButtonGuardarOdonto.setEnabled(true);
            }else{
                JOptionPane.showMessageDialog(rootPane, "No ha Generado ningun Tratamiento", "Generar Tratamiento", JOptionPane.WARNING_MESSAGE);
            }    
        }else{
                JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un Tipo de Odontograma", "Setear Odontograma", JOptionPane.ERROR_MESSAGE);
        }
    }

    public static void pasarDoctorPaciente(Doctor doctor, Paciente paciente){      
        
        elDoctor = doctor;
        elPaciente = paciente;     
    }
    
    /*private void runEventSiguient(String evento) {        
        int i = hallazgosSet.size();
        int j = listaTratamientos.size();
        //eliminar los hallazgos y tratamientos 
        for(int k = 0; k < i; k++)
            hallazgosSet.remove(0);
        
        for(int l = 0; l < j; l++)
            listaTratamientos.remove(0);
        
        modeloH = Configuraciones.limpiarModelo(modeloH);
        modeloT = Configuraciones.limpiarModelo(modeloT);
        
        if(evento.compareToIgnoreCase("Tratamiento paciente actual") == 0){
            //jButtonSelectHallazgo.doClick();
            jButtonSelectTratamiento.doClick();
            mostrarDoctorPaciente();
        }else if(evento.compareToIgnoreCase("Hallazgo paciente actual") == 0){
            //jButtonSelectTratamiento.doClick();
            jButtonSelectHallazgo.doClick();
            mostrarDoctorPaciente();
        }else if(evento.compareToIgnoreCase("Odontograma NewPaciente") == 0){
            elPaciente = null;
            seleccionTipoOdontograma();
            
        }else{
            //finalizar salir    
            this.setVisible(false);
            Inicio jFrame = new Inicio(elUsuario);
            jFrame.setVisible(true);
        }
   }
*/
    
    private void mostrarDoctorPaciente() {
        if(elPaciente!=null){
            jButtonBuscarPaciente.setVisible(false);
            jTextFieldelDoctor.setText(elDoctor.getNombre()+" "+elDoctor.getApellido());
            jTextFieldelPaciente.setText(elPaciente.getNombres()+" "+elPaciente.getApellidos());
        }else{
            jTextFieldelDoctor.setText(elDoctor.getNombre()+" "+elDoctor.getApellido());
            jButtonBuscarPaciente.setEnabled(true);
            jButtonBuscarPaciente.doClick();
        }
    }
    
    //Variables
            
    Diente dienteActual;
    DetalleHallazgo nuevoHallazgo;
    Tratamiento nuevoTratamiento;
    
    private static DefaultTableModel modeloH = new DefaultTableModel(){
        public boolean isCellEditable(int row, int column) {
            return false;
        }};
    private static DefaultTableModel modeloT = new DefaultTableModel(){
        public boolean isCellEditable(int row, int column) {
            return false;
        }};
    
    private static int tipoTransaction = 0;
    public static int diag = 0;
    public static Odontograma odon = null;
    
    private static ArrayList<DetalleHallazgo> hallazgosSet = new ArrayList();
    private static ArrayList<Tratamiento> listaTratamientos = new ArrayList();
    
    public static Paciente elPaciente = null;
    public static Doctor elDoctor;
    public static Usuario elUsuario;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarPaciente;
    private javax.swing.JButton jButtonD11;
    private javax.swing.JButton jButtonD12;
    private javax.swing.JButton jButtonD13;
    private javax.swing.JButton jButtonD14;
    private javax.swing.JButton jButtonD15;
    private javax.swing.JButton jButtonD16;
    private javax.swing.JButton jButtonD17;
    private javax.swing.JButton jButtonD18;
    private javax.swing.JButton jButtonD21;
    private javax.swing.JButton jButtonD22;
    private javax.swing.JButton jButtonD23;
    private javax.swing.JButton jButtonD24;
    private javax.swing.JButton jButtonD25;
    private javax.swing.JButton jButtonD26;
    private javax.swing.JButton jButtonD27;
    private javax.swing.JButton jButtonD28;
    private javax.swing.JButton jButtonD31;
    private javax.swing.JButton jButtonD32;
    private javax.swing.JButton jButtonD33;
    private javax.swing.JButton jButtonD34;
    private javax.swing.JButton jButtonD35;
    private javax.swing.JButton jButtonD36;
    private javax.swing.JButton jButtonD37;
    private javax.swing.JButton jButtonD38;
    private javax.swing.JButton jButtonD41;
    private javax.swing.JButton jButtonD42;
    private javax.swing.JButton jButtonD43;
    private javax.swing.JButton jButtonD44;
    private javax.swing.JButton jButtonD45;
    private javax.swing.JButton jButtonD46;
    private javax.swing.JButton jButtonD47;
    private javax.swing.JButton jButtonD48;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonGuardarOdonto;
    private javax.swing.JButton jButtonSelectHallazgo;
    private javax.swing.JButton jButtonSelectTratamiento;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelElPaciente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAbajoDerecha;
    private javax.swing.JPanel jPanelAbajoIzquierda;
    private javax.swing.JPanel jPanelArribaDerecha;
    private javax.swing.JPanel jPanelArribaIzquierda;
    private javax.swing.JPanel jPanelBoca;
    private javax.swing.JPanel jPanelDatosOdontograma;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableContenedorDatos;
    private javax.swing.JTextField jTextFieldelDoctor;
    private javax.swing.JTextField jTextFieldelPaciente;
    // End of variables declaration//GEN-END:variables

    private void llenarTabla() {
                      
        if(odon.getTipo().compareTo("Examen") == 0){
            ArrayList<DetalleHallazgo> hallEnc = new ArrayList();
            hallEnc = OdontogramaControlador.BuscarHallazgos(odon);
            if(hallEnc != null){
                for(DetalleHallazgo det : hallEnc){
                    cargarTablaHallago(det);
                }
            }
        }else if(odon.getTipo().compareTo("Tratamiento") == 0){
            ArrayList<Tratamiento> tratEnc = new ArrayList();
            tratEnc = OdontogramaControlador.BuscarTratamientos(odon);
            if(tratEnc  != null){
                for(Tratamiento tr : tratEnc){
                    cargarTablaTratamiento(tr);
                }
            }
        }
    }

    private void setearModelo() {
        if(odon.getTipo().compareTo("Examen") == 0){
            jButtonSelectHallazgo.doClick();
        }else if(odon.getTipo().compareTo("Tratamiento") == 0){
            jButtonSelectTratamiento.doClick();
        }
    }

    
}
