package OdontoSysModelo;
// Generated 24/07/2014 08:45:38 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetalleNotaEmp generated by hbm2java
 */
@Entity
@Table(name="detalle_nota_emp"
    ,catalog="odontosys"
)
public class DetalleNotaEmp  implements java.io.Serializable {


     private Integer iddetalleNotaEmp;
     private NotaCreditoEmpresa notaCreditoEmpresa;
     private String descripcion;
     private int monto;

    public DetalleNotaEmp() {
    }

    public DetalleNotaEmp(NotaCreditoEmpresa notaCreditoEmpresa, String descripcion, int monto) {
       this.notaCreditoEmpresa = notaCreditoEmpresa;
       this.descripcion = descripcion;
       this.monto = monto;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="iddetalle_nota_emp", unique=true, nullable=false)
    public Integer getIddetalleNotaEmp() {
        return this.iddetalleNotaEmp;
    }
    
    public void setIddetalleNotaEmp(Integer iddetalleNotaEmp) {
        this.iddetalleNotaEmp = iddetalleNotaEmp;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_notacredemp", nullable=false)
    public NotaCreditoEmpresa getNotaCreditoEmpresa() {
        return this.notaCreditoEmpresa;
    }
    
    public void setNotaCreditoEmpresa(NotaCreditoEmpresa notaCreditoEmpresa) {
        this.notaCreditoEmpresa = notaCreditoEmpresa;
    }

    
    @Column(name="descripcion", nullable=false, length=70)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="monto", nullable=false)
    public int getMonto() {
        return this.monto;
    }
    
    public void setMonto(int monto) {
        this.monto = monto;
    }




}


