package OdontoSysModelo;
// Generated 24/07/2014 08:45:38 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Diente generated by hbm2java
 */
@Entity
@Table(name="diente"
    ,catalog="odontosys"
)
public class Diente  implements java.io.Serializable {


     private Integer iddiente;
     private String nombre;
     private int nomenclatura;
     private Set<DetalleHallazgo> detalleHallazgos = new HashSet<DetalleHallazgo>(0);
     private Set<Tratamiento> tratamientos = new HashSet<Tratamiento>(0);

    public Diente() {
    }

	
    public Diente(String nombre, int nomenclatura) {
        this.nombre = nombre;
        this.nomenclatura = nomenclatura;
    }
    public Diente(String nombre, int nomenclatura, Set<DetalleHallazgo> detalleHallazgos, Set<Tratamiento> tratamientos) {
       this.nombre = nombre;
       this.nomenclatura = nomenclatura;
       this.detalleHallazgos = detalleHallazgos;
       this.tratamientos = tratamientos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="iddiente", unique=true, nullable=false)
    public Integer getIddiente() {
        return this.iddiente;
    }
    
    public void setIddiente(Integer iddiente) {
        this.iddiente = iddiente;
    }

    
    @Column(name="nombre", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="nomenclatura", nullable=false)
    public int getNomenclatura() {
        return this.nomenclatura;
    }
    
    public void setNomenclatura(int nomenclatura) {
        this.nomenclatura = nomenclatura;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="diente")
    public Set<DetalleHallazgo> getDetalleHallazgos() {
        return this.detalleHallazgos;
    }
    
    public void setDetalleHallazgos(Set<DetalleHallazgo> detalleHallazgos) {
        this.detalleHallazgos = detalleHallazgos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="diente")
    public Set<Tratamiento> getTratamientos() {
        return this.tratamientos;
    }
    
    public void setTratamientos(Set<Tratamiento> tratamientos) {
        this.tratamientos = tratamientos;
    }




}


