package OdontoSysModelo;
// Generated 24/07/2014 08:45:38 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Empresa generated by hbm2java
 */
@Entity
@Table(name="empresa"
    ,catalog="odontosys"
)
public class Empresa  implements java.io.Serializable {


     private Integer idempresa;
     private String nombre;
     private int ruc;
     private String direccion;
     private String telefono;
     private String email;
     private String nombreContacto;
     private String telContacto;
     private String observaciones;
     private String estado;
     private Set<Convenio> convenios = new HashSet<Convenio>(0);
     private Set<FacturaConvenio> facturaConvenios = new HashSet<FacturaConvenio>(0);
     private Set<ReciboEmpresa> reciboEmpresas = new HashSet<ReciboEmpresa>(0);
     private Set<MovimientoEmpresa> movimientoEmpresas = new HashSet<MovimientoEmpresa>(0);
     private Set<NotaCreditoEmpresa> notaCreditoEmpresas = new HashSet<NotaCreditoEmpresa>(0);
     private Set<FacturaEmpresa> facturaEmpresas = new HashSet<FacturaEmpresa>(0);

    public Empresa() {
    }

	
    public Empresa(String nombre, int ruc, String direccion, String telefono, String estado) {
        this.nombre = nombre;
        this.ruc = ruc;
        this.direccion = direccion;
        this.telefono = telefono;
        this.estado = estado;
    }
    public Empresa(String nombre, int ruc, String direccion, String telefono, String email, String nombreContacto, String telContacto, String observaciones, String estado, Set<Convenio> convenios, Set<FacturaConvenio> facturaConvenios, Set<ReciboEmpresa> reciboEmpresas, Set<MovimientoEmpresa> movimientoEmpresas, Set<NotaCreditoEmpresa> notaCreditoEmpresas, Set<FacturaEmpresa> facturaEmpresas) {
       this.nombre = nombre;
       this.ruc = ruc;
       this.direccion = direccion;
       this.telefono = telefono;
       this.email = email;
       this.nombreContacto = nombreContacto;
       this.telContacto = telContacto;
       this.observaciones = observaciones;
       this.estado = estado;
       this.convenios = convenios;
       this.facturaConvenios = facturaConvenios;
       this.reciboEmpresas = reciboEmpresas;
       this.movimientoEmpresas = movimientoEmpresas;
       this.notaCreditoEmpresas = notaCreditoEmpresas;
       this.facturaEmpresas = facturaEmpresas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idempresa", unique=true, nullable=false)
    public Integer getIdempresa() {
        return this.idempresa;
    }
    
    public void setIdempresa(Integer idempresa) {
        this.idempresa = idempresa;
    }

    
    @Column(name="nombre", nullable=false, length=100)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="ruc", nullable=false)
    public int getRuc() {
        return this.ruc;
    }
    
    public void setRuc(int ruc) {
        this.ruc = ruc;
    }

    
    @Column(name="direccion", nullable=false, length=100)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="telefono", nullable=false, length=20)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="email", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="nombre_contacto", length=100)
    public String getNombreContacto() {
        return this.nombreContacto;
    }
    
    public void setNombreContacto(String nombreContacto) {
        this.nombreContacto = nombreContacto;
    }

    
    @Column(name="tel_contacto", length=20)
    public String getTelContacto() {
        return this.telContacto;
    }
    
    public void setTelContacto(String telContacto) {
        this.telContacto = telContacto;
    }

    
    @Column(name="observaciones", length=300)
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    
    @Column(name="estado", nullable=false, length=8)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set<Convenio> getConvenios() {
        return this.convenios;
    }
    
    public void setConvenios(Set<Convenio> convenios) {
        this.convenios = convenios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set<FacturaConvenio> getFacturaConvenios() {
        return this.facturaConvenios;
    }
    
    public void setFacturaConvenios(Set<FacturaConvenio> facturaConvenios) {
        this.facturaConvenios = facturaConvenios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set<ReciboEmpresa> getReciboEmpresas() {
        return this.reciboEmpresas;
    }
    
    public void setReciboEmpresas(Set<ReciboEmpresa> reciboEmpresas) {
        this.reciboEmpresas = reciboEmpresas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set<MovimientoEmpresa> getMovimientoEmpresas() {
        return this.movimientoEmpresas;
    }
    
    public void setMovimientoEmpresas(Set<MovimientoEmpresa> movimientoEmpresas) {
        this.movimientoEmpresas = movimientoEmpresas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set<NotaCreditoEmpresa> getNotaCreditoEmpresas() {
        return this.notaCreditoEmpresas;
    }
    
    public void setNotaCreditoEmpresas(Set<NotaCreditoEmpresa> notaCreditoEmpresas) {
        this.notaCreditoEmpresas = notaCreditoEmpresas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set<FacturaEmpresa> getFacturaEmpresas() {
        return this.facturaEmpresas;
    }
    
    public void setFacturaEmpresas(Set<FacturaEmpresa> facturaEmpresas) {
        this.facturaEmpresas = facturaEmpresas;
    }




}


