package OdontoSysModelo;
// Generated 24/07/2014 08:45:38 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Movimiento generated by hbm2java
 */
@Entity
@Table(name="movimiento"
    ,catalog="odontosys"
)
public class Movimiento  implements java.io.Serializable {


     private Integer idmovimiento;
     private Recibo recibo;
     private NotaCredito notaCredito;
     private Factura factura;
     private Paciente paciente;
     private Date fecha;
     private String movimiento;
     private int debe;
     private int haber;
     private Set<Caja> cajas = new HashSet<Caja>(0);

    public Movimiento() {
    }

	
    public Movimiento(Paciente paciente, Date fecha, String movimiento, int debe, int haber) {
        this.paciente = paciente;
        this.fecha = fecha;
        this.movimiento = movimiento;
        this.debe = debe;
        this.haber = haber;
    }
    public Movimiento(Recibo recibo, NotaCredito notaCredito, Factura factura, Paciente paciente, Date fecha, String movimiento, int debe, int haber, Set<Caja> cajas) {
       this.recibo = recibo;
       this.notaCredito = notaCredito;
       this.factura = factura;
       this.paciente = paciente;
       this.fecha = fecha;
       this.movimiento = movimiento;
       this.debe = debe;
       this.haber = haber;
       this.cajas = cajas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idmovimiento", unique=true, nullable=false)
    public Integer getIdmovimiento() {
        return this.idmovimiento;
    }
    
    public void setIdmovimiento(Integer idmovimiento) {
        this.idmovimiento = idmovimiento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_recibo")
    public Recibo getRecibo() {
        return this.recibo;
    }
    
    public void setRecibo(Recibo recibo) {
        this.recibo = recibo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_nota")
    public NotaCredito getNotaCredito() {
        return this.notaCredito;
    }
    
    public void setNotaCredito(NotaCredito notaCredito) {
        this.notaCredito = notaCredito;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_factura")
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_paciente", nullable=false)
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="movimiento", nullable=false, length=100)
    public String getMovimiento() {
        return this.movimiento;
    }
    
    public void setMovimiento(String movimiento) {
        this.movimiento = movimiento;
    }

    
    @Column(name="debe", nullable=false)
    public int getDebe() {
        return this.debe;
    }
    
    public void setDebe(int debe) {
        this.debe = debe;
    }

    
    @Column(name="haber", nullable=false)
    public int getHaber() {
        return this.haber;
    }
    
    public void setHaber(int haber) {
        this.haber = haber;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="movimiento")
    public Set<Caja> getCajas() {
        return this.cajas;
    }
    
    public void setCajas(Set<Caja> cajas) {
        this.cajas = cajas;
    }




}


