package OdontoSysModelo;
// Generated 24/07/2014 08:45:38 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MovimientoEmpresa generated by hbm2java
 */
@Entity
@Table(name="movimiento_empresa"
    ,catalog="odontosys"
)
public class MovimientoEmpresa  implements java.io.Serializable {


     private Integer idmovimientoEmpresa;
     private ReciboEmpresa reciboEmpresa;
     private FacturaEmpresa facturaEmpresa;
     private Empresa empresa;
     private NotaCreditoEmpresa notaCreditoEmpresa;
     private Date fecha;
     private String movimiento;
     private int debe;
     private int haber;
     private Set<Caja> cajas = new HashSet<Caja>(0);

    public MovimientoEmpresa() {
    }

	
    public MovimientoEmpresa(Empresa empresa, Date fecha, String movimiento, int debe, int haber) {
        this.empresa = empresa;
        this.fecha = fecha;
        this.movimiento = movimiento;
        this.debe = debe;
        this.haber = haber;
    }
    public MovimientoEmpresa(ReciboEmpresa reciboEmpresa, FacturaEmpresa facturaEmpresa, Empresa empresa, NotaCreditoEmpresa notaCreditoEmpresa, Date fecha, String movimiento, int debe, int haber, Set<Caja> cajas) {
       this.reciboEmpresa = reciboEmpresa;
       this.facturaEmpresa = facturaEmpresa;
       this.empresa = empresa;
       this.notaCreditoEmpresa = notaCreditoEmpresa;
       this.fecha = fecha;
       this.movimiento = movimiento;
       this.debe = debe;
       this.haber = haber;
       this.cajas = cajas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idmovimiento_empresa", unique=true, nullable=false)
    public Integer getIdmovimientoEmpresa() {
        return this.idmovimientoEmpresa;
    }
    
    public void setIdmovimientoEmpresa(Integer idmovimientoEmpresa) {
        this.idmovimientoEmpresa = idmovimientoEmpresa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_recibo")
    public ReciboEmpresa getReciboEmpresa() {
        return this.reciboEmpresa;
    }
    
    public void setReciboEmpresa(ReciboEmpresa reciboEmpresa) {
        this.reciboEmpresa = reciboEmpresa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_factura")
    public FacturaEmpresa getFacturaEmpresa() {
        return this.facturaEmpresa;
    }
    
    public void setFacturaEmpresa(FacturaEmpresa facturaEmpresa) {
        this.facturaEmpresa = facturaEmpresa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_empresa", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_nota")
    public NotaCreditoEmpresa getNotaCreditoEmpresa() {
        return this.notaCreditoEmpresa;
    }
    
    public void setNotaCreditoEmpresa(NotaCreditoEmpresa notaCreditoEmpresa) {
        this.notaCreditoEmpresa = notaCreditoEmpresa;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="movimiento", nullable=false, length=100)
    public String getMovimiento() {
        return this.movimiento;
    }
    
    public void setMovimiento(String movimiento) {
        this.movimiento = movimiento;
    }

    
    @Column(name="debe", nullable=false)
    public int getDebe() {
        return this.debe;
    }
    
    public void setDebe(int debe) {
        this.debe = debe;
    }

    
    @Column(name="haber", nullable=false)
    public int getHaber() {
        return this.haber;
    }
    
    public void setHaber(int haber) {
        this.haber = haber;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="movimientoEmpresa")
    public Set<Caja> getCajas() {
        return this.cajas;
    }
    
    public void setCajas(Set<Caja> cajas) {
        this.cajas = cajas;
    }




}


