package OdontoSysModelo;
// Generated 24/07/2014 08:45:38 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NotaCredito generated by hbm2java
 */
@Entity
@Table(name="nota_credito"
    ,catalog="odontosys"
)
public class NotaCredito  implements java.io.Serializable {


     private Integer idnotaCredito;
     private Factura factura;
     private Usuario usuario;
     private Paciente paciente;
     private Date fecha;
     private int total;
     private Set<Movimiento> movimientos = new HashSet<Movimiento>(0);
     private Set<DetalleNota> detalleNotas = new HashSet<DetalleNota>(0);

    public NotaCredito() {
    }

	
    public NotaCredito(Factura factura, Usuario usuario, Paciente paciente, Date fecha, int total) {
        this.factura = factura;
        this.usuario = usuario;
        this.paciente = paciente;
        this.fecha = fecha;
        this.total = total;
    }
    public NotaCredito(Factura factura, Usuario usuario, Paciente paciente, Date fecha, int total, Set<Movimiento> movimientos, Set<DetalleNota> detalleNotas) {
       this.factura = factura;
       this.usuario = usuario;
       this.paciente = paciente;
       this.fecha = fecha;
       this.total = total;
       this.movimientos = movimientos;
       this.detalleNotas = detalleNotas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idnota_credito", unique=true, nullable=false)
    public Integer getIdnotaCredito() {
        return this.idnotaCredito;
    }
    
    public void setIdnotaCredito(Integer idnotaCredito) {
        this.idnotaCredito = idnotaCredito;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_factura", nullable=false)
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_usuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_paciente", nullable=false)
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="total", nullable=false)
    public int getTotal() {
        return this.total;
    }
    
    public void setTotal(int total) {
        this.total = total;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="notaCredito")
    public Set<Movimiento> getMovimientos() {
        return this.movimientos;
    }
    
    public void setMovimientos(Set<Movimiento> movimientos) {
        this.movimientos = movimientos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="notaCredito")
    public Set<DetalleNota> getDetalleNotas() {
        return this.detalleNotas;
    }
    
    public void setDetalleNotas(Set<DetalleNota> detalleNotas) {
        this.detalleNotas = detalleNotas;
    }




}


