package OdontoSysModelo;
// Generated 24/07/2014 08:45:38 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NotaCreditoEmpresa generated by hbm2java
 */
@Entity
@Table(name="nota_credito_empresa"
    ,catalog="odontosys"
)
public class NotaCreditoEmpresa  implements java.io.Serializable {


     private Integer idnotaCreditoEmpresa;
     private Empresa empresa;
     private Usuario usuario;
     private FacturaEmpresa facturaEmpresa;
     private Date fecha;
     private int total;
     private Set<MovimientoEmpresa> movimientoEmpresas = new HashSet<MovimientoEmpresa>(0);
     private Set<DetalleNotaEmp> detalleNotaEmps = new HashSet<DetalleNotaEmp>(0);

    public NotaCreditoEmpresa() {
    }

	
    public NotaCreditoEmpresa(Empresa empresa, Usuario usuario, FacturaEmpresa facturaEmpresa, Date fecha, int total) {
        this.empresa = empresa;
        this.usuario = usuario;
        this.facturaEmpresa = facturaEmpresa;
        this.fecha = fecha;
        this.total = total;
    }
    public NotaCreditoEmpresa(Empresa empresa, Usuario usuario, FacturaEmpresa facturaEmpresa, Date fecha, int total, Set<MovimientoEmpresa> movimientoEmpresas, Set<DetalleNotaEmp> detalleNotaEmps) {
       this.empresa = empresa;
       this.usuario = usuario;
       this.facturaEmpresa = facturaEmpresa;
       this.fecha = fecha;
       this.total = total;
       this.movimientoEmpresas = movimientoEmpresas;
       this.detalleNotaEmps = detalleNotaEmps;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idnota_credito_empresa", unique=true, nullable=false)
    public Integer getIdnotaCreditoEmpresa() {
        return this.idnotaCreditoEmpresa;
    }
    
    public void setIdnotaCreditoEmpresa(Integer idnotaCreditoEmpresa) {
        this.idnotaCreditoEmpresa = idnotaCreditoEmpresa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_empresa", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_usuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_facturaemp", nullable=false)
    public FacturaEmpresa getFacturaEmpresa() {
        return this.facturaEmpresa;
    }
    
    public void setFacturaEmpresa(FacturaEmpresa facturaEmpresa) {
        this.facturaEmpresa = facturaEmpresa;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="total", nullable=false)
    public int getTotal() {
        return this.total;
    }
    
    public void setTotal(int total) {
        this.total = total;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="notaCreditoEmpresa")
    public Set<MovimientoEmpresa> getMovimientoEmpresas() {
        return this.movimientoEmpresas;
    }
    
    public void setMovimientoEmpresas(Set<MovimientoEmpresa> movimientoEmpresas) {
        this.movimientoEmpresas = movimientoEmpresas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="notaCreditoEmpresa")
    public Set<DetalleNotaEmp> getDetalleNotaEmps() {
        return this.detalleNotaEmps;
    }
    
    public void setDetalleNotaEmps(Set<DetalleNotaEmp> detalleNotaEmps) {
        this.detalleNotaEmps = detalleNotaEmps;
    }




}


