package OdontoSysModelo;
// Generated 24/07/2014 08:45:38 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Odontograma generated by hbm2java
 */
@Entity
@Table(name="odontograma"
    ,catalog="odontosys"
)
public class Odontograma  implements java.io.Serializable {


     private Integer idodontograma;
     private Paciente paciente;
     private Doctor doctor;
     private Date fecha;
     private String tipo;
     private Set<Diagnostico> diagnosticos = new HashSet<Diagnostico>(0);
     private Set<OrdenServicio> ordenServicios = new HashSet<OrdenServicio>(0);
     private Set<DetalleHallazgo> detalleHallazgos = new HashSet<DetalleHallazgo>(0);
     private Set<Tratamiento> tratamientos = new HashSet<Tratamiento>(0);

    public Odontograma() {
    }

	
    public Odontograma(Paciente paciente, Doctor doctor, Date fecha, String tipo) {
        this.paciente = paciente;
        this.doctor = doctor;
        this.fecha = fecha;
        this.tipo = tipo;
    }
    public Odontograma(Paciente paciente, Doctor doctor, Date fecha, String tipo, Set<Diagnostico> diagnosticos, Set<OrdenServicio> ordenServicios, Set<DetalleHallazgo> detalleHallazgos, Set<Tratamiento> tratamientos) {
       this.paciente = paciente;
       this.doctor = doctor;
       this.fecha = fecha;
       this.tipo = tipo;
       this.diagnosticos = diagnosticos;
       this.ordenServicios = ordenServicios;
       this.detalleHallazgos = detalleHallazgos;
       this.tratamientos = tratamientos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idodontograma", unique=true, nullable=false)
    public Integer getIdodontograma() {
        return this.idodontograma;
    }
    
    public void setIdodontograma(Integer idodontograma) {
        this.idodontograma = idodontograma;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_paciente", nullable=false)
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_doctor", nullable=false)
    public Doctor getDoctor() {
        return this.doctor;
    }
    
    public void setDoctor(Doctor doctor) {
        this.doctor = doctor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="tipo", nullable=false, length=20)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="odontograma")
    public Set<Diagnostico> getDiagnosticos() {
        return this.diagnosticos;
    }
    
    public void setDiagnosticos(Set<Diagnostico> diagnosticos) {
        this.diagnosticos = diagnosticos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="odontograma")
    public Set<OrdenServicio> getOrdenServicios() {
        return this.ordenServicios;
    }
    
    public void setOrdenServicios(Set<OrdenServicio> ordenServicios) {
        this.ordenServicios = ordenServicios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="odontograma")
    public Set<DetalleHallazgo> getDetalleHallazgos() {
        return this.detalleHallazgos;
    }
    
    public void setDetalleHallazgos(Set<DetalleHallazgo> detalleHallazgos) {
        this.detalleHallazgos = detalleHallazgos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="odontograma")
    public Set<Tratamiento> getTratamientos() {
        return this.tratamientos;
    }
    
    public void setTratamientos(Set<Tratamiento> tratamientos) {
        this.tratamientos = tratamientos;
    }




}


