package OdontoSysModelo;
// Generated 24/07/2014 08:45:38 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Paciente generated by hbm2java
 */
@Entity
@Table(name="paciente"
    ,catalog="odontosys"
)
public class Paciente  implements java.io.Serializable {


     private Integer idPaciente;
     private String nombres;
     private String apellidos;
     private int nroCi;
     private Date fechaNac;
     private String sexo;
     private String telLb;
     private String telCel;
     private String direccion;
     private String ciudad;
     private String email;
     private int peso;
     private String enfermedades;
     private String medicamentos;
     private String alergias;
     private String cirugias;
     private String observaciones;
     private String estado;
     private Set<Factura> facturas = new HashSet<Factura>(0);
     private Set<Agenda> agendas = new HashSet<Agenda>(0);
     private Set<OrdenServicio> ordenServicios = new HashSet<OrdenServicio>(0);
     private Set<Diagnostico> diagnosticos = new HashSet<Diagnostico>(0);
     private Set<Movimiento> movimientos = new HashSet<Movimiento>(0);
     private Set<Convenio> convenios = new HashSet<Convenio>(0);
     private Set<Odontograma> odontogramas = new HashSet<Odontograma>(0);
     private Set<Recibo> recibos = new HashSet<Recibo>(0);
     private Set<NotaCredito> notaCreditos = new HashSet<NotaCredito>(0);

    public Paciente() {
    }

	
    public Paciente(String nombres, String apellidos, int nroCi, Date fechaNac, String sexo, String direccion, String ciudad, int peso, String enfermedades, String medicamentos, String alergias, String cirugias, String observaciones, String estado) {
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.nroCi = nroCi;
        this.fechaNac = fechaNac;
        this.sexo = sexo;
        this.direccion = direccion;
        this.ciudad = ciudad;
        this.peso = peso;
        this.enfermedades = enfermedades;
        this.medicamentos = medicamentos;
        this.alergias = alergias;
        this.cirugias = cirugias;
        this.observaciones = observaciones;
        this.estado = estado;
    }
    public Paciente(String nombres, String apellidos, int nroCi, Date fechaNac, String sexo, String telLb, String telCel, String direccion, String ciudad, String email, int peso, String enfermedades, String medicamentos, String alergias, String cirugias, String observaciones, String estado, Set<Factura> facturas, Set<Agenda> agendas, Set<OrdenServicio> ordenServicios, Set<Diagnostico> diagnosticos, Set<Movimiento> movimientos, Set<Convenio> convenios, Set<Odontograma> odontogramas, Set<Recibo> recibos, Set<NotaCredito> notaCreditos) {
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.nroCi = nroCi;
       this.fechaNac = fechaNac;
       this.sexo = sexo;
       this.telLb = telLb;
       this.telCel = telCel;
       this.direccion = direccion;
       this.ciudad = ciudad;
       this.email = email;
       this.peso = peso;
       this.enfermedades = enfermedades;
       this.medicamentos = medicamentos;
       this.alergias = alergias;
       this.cirugias = cirugias;
       this.observaciones = observaciones;
       this.estado = estado;
       this.facturas = facturas;
       this.agendas = agendas;
       this.ordenServicios = ordenServicios;
       this.diagnosticos = diagnosticos;
       this.movimientos = movimientos;
       this.convenios = convenios;
       this.odontogramas = odontogramas;
       this.recibos = recibos;
       this.notaCreditos = notaCreditos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idPaciente", unique=true, nullable=false)
    public Integer getIdPaciente() {
        return this.idPaciente;
    }
    
    public void setIdPaciente(Integer idPaciente) {
        this.idPaciente = idPaciente;
    }

    
    @Column(name="Nombres", nullable=false)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    
    @Column(name="Apellidos", nullable=false)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    
    @Column(name="Nro_CI", nullable=false)
    public int getNroCi() {
        return this.nroCi;
    }
    
    public void setNroCi(int nroCi) {
        this.nroCi = nroCi;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Fecha_Nac", nullable=false, length=10)
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }

    
    @Column(name="Sexo", nullable=false, length=1)
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    
    @Column(name="Tel_LB", length=20)
    public String getTelLb() {
        return this.telLb;
    }
    
    public void setTelLb(String telLb) {
        this.telLb = telLb;
    }

    
    @Column(name="Tel_Cel", length=10)
    public String getTelCel() {
        return this.telCel;
    }
    
    public void setTelCel(String telCel) {
        this.telCel = telCel;
    }

    
    @Column(name="Direccion", nullable=false, length=500)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="Ciudad", nullable=false, length=100)
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }

    
    @Column(name="Email", length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="Peso", nullable=false)
    public int getPeso() {
        return this.peso;
    }
    
    public void setPeso(int peso) {
        this.peso = peso;
    }

    
    @Column(name="Enfermedades", nullable=false, length=500)
    public String getEnfermedades() {
        return this.enfermedades;
    }
    
    public void setEnfermedades(String enfermedades) {
        this.enfermedades = enfermedades;
    }

    
    @Column(name="Medicamentos", nullable=false, length=500)
    public String getMedicamentos() {
        return this.medicamentos;
    }
    
    public void setMedicamentos(String medicamentos) {
        this.medicamentos = medicamentos;
    }

    
    @Column(name="Alergias", nullable=false, length=500)
    public String getAlergias() {
        return this.alergias;
    }
    
    public void setAlergias(String alergias) {
        this.alergias = alergias;
    }

    
    @Column(name="Cirugias", nullable=false, length=500)
    public String getCirugias() {
        return this.cirugias;
    }
    
    public void setCirugias(String cirugias) {
        this.cirugias = cirugias;
    }

    
    @Column(name="Observaciones", nullable=false, length=1000)
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    
    @Column(name="estado", nullable=false, length=8)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="paciente")
    public Set<Factura> getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set<Factura> facturas) {
        this.facturas = facturas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="paciente")
    public Set<Agenda> getAgendas() {
        return this.agendas;
    }
    
    public void setAgendas(Set<Agenda> agendas) {
        this.agendas = agendas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="paciente")
    public Set<OrdenServicio> getOrdenServicios() {
        return this.ordenServicios;
    }
    
    public void setOrdenServicios(Set<OrdenServicio> ordenServicios) {
        this.ordenServicios = ordenServicios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="paciente")
    public Set<Diagnostico> getDiagnosticos() {
        return this.diagnosticos;
    }
    
    public void setDiagnosticos(Set<Diagnostico> diagnosticos) {
        this.diagnosticos = diagnosticos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="paciente")
    public Set<Movimiento> getMovimientos() {
        return this.movimientos;
    }
    
    public void setMovimientos(Set<Movimiento> movimientos) {
        this.movimientos = movimientos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="paciente")
    public Set<Convenio> getConvenios() {
        return this.convenios;
    }
    
    public void setConvenios(Set<Convenio> convenios) {
        this.convenios = convenios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="paciente")
    public Set<Odontograma> getOdontogramas() {
        return this.odontogramas;
    }
    
    public void setOdontogramas(Set<Odontograma> odontogramas) {
        this.odontogramas = odontogramas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="paciente")
    public Set<Recibo> getRecibos() {
        return this.recibos;
    }
    
    public void setRecibos(Set<Recibo> recibos) {
        this.recibos = recibos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="paciente")
    public Set<NotaCredito> getNotaCreditos() {
        return this.notaCreditos;
    }
    
    public void setNotaCreditos(Set<NotaCredito> notaCreditos) {
        this.notaCreditos = notaCreditos;
    }




}


