package OdontoSysModelo;
// Generated 24/07/2014 08:45:38 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="odontosys"
)
public class Usuario  implements java.io.Serializable {


     private Integer idusuario;
     private Doctor doctor;
     private String nombre;
     private String passw;
     private String rol;
     private String estado;
     private String observacion;
     private Set<ReciboEmpresa> reciboEmpresas = new HashSet<ReciboEmpresa>(0);
     private Set<NotaCredito> notaCreditos = new HashSet<NotaCredito>(0);
     private Set<NotaCreditoEmpresa> notaCreditoEmpresas = new HashSet<NotaCreditoEmpresa>(0);
     private Set<Recibo> recibos = new HashSet<Recibo>(0);

    public Usuario() {
    }

	
    public Usuario(String nombre, String passw, String rol, String estado) {
        this.nombre = nombre;
        this.passw = passw;
        this.rol = rol;
        this.estado = estado;
    }
    public Usuario(Doctor doctor, String nombre, String passw, String rol, String estado, String observacion, Set<ReciboEmpresa> reciboEmpresas, Set<NotaCredito> notaCreditos, Set<NotaCreditoEmpresa> notaCreditoEmpresas, Set<Recibo> recibos) {
       this.doctor = doctor;
       this.nombre = nombre;
       this.passw = passw;
       this.rol = rol;
       this.estado = estado;
       this.observacion = observacion;
       this.reciboEmpresas = reciboEmpresas;
       this.notaCreditos = notaCreditos;
       this.notaCreditoEmpresas = notaCreditoEmpresas;
       this.recibos = recibos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idusuario", unique=true, nullable=false)
    public Integer getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(Integer idusuario) {
        this.idusuario = idusuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_asoc")
    public Doctor getDoctor() {
        return this.doctor;
    }
    
    public void setDoctor(Doctor doctor) {
        this.doctor = doctor;
    }

    
    @Column(name="nombre", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="passw", nullable=false, length=50)
    public String getPassw() {
        return this.passw;
    }
    
    public void setPassw(String passw) {
        this.passw = passw;
    }

    
    @Column(name="rol", nullable=false, length=45)
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }

    
    @Column(name="estado", nullable=false, length=45)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="observacion", length=100)
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set<ReciboEmpresa> getReciboEmpresas() {
        return this.reciboEmpresas;
    }
    
    public void setReciboEmpresas(Set<ReciboEmpresa> reciboEmpresas) {
        this.reciboEmpresas = reciboEmpresas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set<NotaCredito> getNotaCreditos() {
        return this.notaCreditos;
    }
    
    public void setNotaCreditos(Set<NotaCredito> notaCreditos) {
        this.notaCreditos = notaCreditos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set<NotaCreditoEmpresa> getNotaCreditoEmpresas() {
        return this.notaCreditoEmpresas;
    }
    
    public void setNotaCreditoEmpresas(Set<NotaCreditoEmpresa> notaCreditoEmpresas) {
        this.notaCreditoEmpresas = notaCreditoEmpresas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set<Recibo> getRecibos() {
        return this.recibos;
    }
    
    public void setRecibos(Set<Recibo> recibos) {
        this.recibos = recibos;
    }




}


