package OdontoSysModelo;
// Generated 24/07/2014 08:45:38 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Agenda generated by hbm2java
 */
@Entity
@Table(name="agenda"
    ,catalog="odontosys"
)
public class Agenda  implements java.io.Serializable {


     private Integer idAgenda;
     private OrdenServicio ordenServicio;
     private Servicio servicio;
     private Paciente paciente;
     private Doctor doctor;
     private Date fecha;
     private String hora;
     private String estado;

    public Agenda() {
    }

	
    public Agenda(Servicio servicio, Paciente paciente, Doctor doctor, Date fecha, String hora, String estado) {
        this.servicio = servicio;
        this.paciente = paciente;
        this.doctor = doctor;
        this.fecha = fecha;
        this.hora = hora;
        this.estado = estado;
    }
    public Agenda(OrdenServicio ordenServicio, Servicio servicio, Paciente paciente, Doctor doctor, Date fecha, String hora, String estado) {
       this.ordenServicio = ordenServicio;
       this.servicio = servicio;
       this.paciente = paciente;
       this.doctor = doctor;
       this.fecha = fecha;
       this.hora = hora;
       this.estado = estado;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idAgenda", unique=true, nullable=false)
    public Integer getIdAgenda() {
        return this.idAgenda;
    }
    
    public void setIdAgenda(Integer idAgenda) {
        this.idAgenda = idAgenda;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_orden")
    public OrdenServicio getOrdenServicio() {
        return this.ordenServicio;
    }
    
    public void setOrdenServicio(OrdenServicio ordenServicio) {
        this.ordenServicio = ordenServicio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="motivo", nullable=false)
    public Servicio getServicio() {
        return this.servicio;
    }
    
    public void setServicio(Servicio servicio) {
        this.servicio = servicio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_paciente", nullable=false)
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_doctor", nullable=false)
    public Doctor getDoctor() {
        return this.doctor;
    }
    
    public void setDoctor(Doctor doctor) {
        this.doctor = doctor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="hora", nullable=false, length=5)
    public String getHora() {
        return this.hora;
    }
    
    public void setHora(String hora) {
        this.hora = hora;
    }

    
    @Column(name="estado", nullable=false, length=20)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


