package OdontoSysModelo;
// Generated 24/07/2014 08:45:38 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Doctor generated by hbm2java
 */
@Entity
@Table(name="doctor"
    ,catalog="odontosys"
)
public class Doctor  implements java.io.Serializable {


     private Integer idDoctor;
     private String nombre;
     private String apellido;
     private int nroCi;
     private Date fechaNac;
     private String sexo;
     private String teLb;
     private String telCel;
     private String direccion;
     private String ciudad;
     private String email;
     private String regProf;
     private String estado;
     private Set<Agenda> agendas = new HashSet<Agenda>(0);
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);
     private Set<Diagnostico> diagnosticos = new HashSet<Diagnostico>(0);
     private Set<Odontograma> odontogramas = new HashSet<Odontograma>(0);

    public Doctor() {
    }

	
    public Doctor(String nombre, String apellido, int nroCi, Date fechaNac, String sexo, String direccion, String ciudad, String regProf) {
        this.nombre = nombre;
        this.apellido = apellido;
        this.nroCi = nroCi;
        this.fechaNac = fechaNac;
        this.sexo = sexo;
        this.direccion = direccion;
        this.ciudad = ciudad;
        this.regProf = regProf;
    }
    public Doctor(String nombre, String apellido, int nroCi, Date fechaNac, String sexo, String teLb, String telCel, String direccion, String ciudad, String email, String regProf, String estado, Set<Agenda> agendas, Set<Usuario> usuarios, Set<Diagnostico> diagnosticos, Set<Odontograma> odontogramas) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.nroCi = nroCi;
       this.fechaNac = fechaNac;
       this.sexo = sexo;
       this.teLb = teLb;
       this.telCel = telCel;
       this.direccion = direccion;
       this.ciudad = ciudad;
       this.email = email;
       this.regProf = regProf;
       this.estado = estado;
       this.agendas = agendas;
       this.usuarios = usuarios;
       this.diagnosticos = diagnosticos;
       this.odontogramas = odontogramas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idDoctor", unique=true, nullable=false)
    public Integer getIdDoctor() {
        return this.idDoctor;
    }
    
    public void setIdDoctor(Integer idDoctor) {
        this.idDoctor = idDoctor;
    }

    
    @Column(name="Nombre", nullable=false)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="Apellido", nullable=false)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="Nro_CI", nullable=false)
    public int getNroCi() {
        return this.nroCi;
    }
    
    public void setNroCi(int nroCi) {
        this.nroCi = nroCi;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Fecha_Nac", nullable=false, length=10)
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }

    
    @Column(name="Sexo", nullable=false, length=1)
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    
    @Column(name="Te_LB", length=20)
    public String getTeLb() {
        return this.teLb;
    }
    
    public void setTeLb(String teLb) {
        this.teLb = teLb;
    }

    
    @Column(name="Tel_Cel", length=10)
    public String getTelCel() {
        return this.telCel;
    }
    
    public void setTelCel(String telCel) {
        this.telCel = telCel;
    }

    
    @Column(name="Direccion", nullable=false, length=500)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="Ciudad", nullable=false, length=50)
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }

    
    @Column(name="Email", length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="Reg_Prof", nullable=false, length=50)
    public String getRegProf() {
        return this.regProf;
    }
    
    public void setRegProf(String regProf) {
        this.regProf = regProf;
    }

    
    @Column(name="estado", length=8)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="doctor")
    public Set<Agenda> getAgendas() {
        return this.agendas;
    }
    
    public void setAgendas(Set<Agenda> agendas) {
        this.agendas = agendas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="doctor")
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="doctor")
    public Set<Diagnostico> getDiagnosticos() {
        return this.diagnosticos;
    }
    
    public void setDiagnosticos(Set<Diagnostico> diagnosticos) {
        this.diagnosticos = diagnosticos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="doctor")
    public Set<Odontograma> getOdontogramas() {
        return this.odontogramas;
    }
    
    public void setOdontogramas(Set<Odontograma> odontogramas) {
        this.odontogramas = odontogramas;
    }




}


