package OdontoSysModelo;
// Generated 24/07/2014 08:45:38 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Hallazgo generated by hbm2java
 */
@Entity
@Table(name="hallazgo"
    ,catalog="odontosys"
)
public class Hallazgo  implements java.io.Serializable {


     private Integer idhallazgo;
     private String nombre;
     private String simbolol;
     private Set<DetalleHallazgo> detalleHallazgos = new HashSet<DetalleHallazgo>(0);

    public Hallazgo() {
    }

	
    public Hallazgo(String nombre) {
        this.nombre = nombre;
    }
    public Hallazgo(String nombre, String simbolol, Set<DetalleHallazgo> detalleHallazgos) {
       this.nombre = nombre;
       this.simbolol = simbolol;
       this.detalleHallazgos = detalleHallazgos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idhallazgo", unique=true, nullable=false)
    public Integer getIdhallazgo() {
        return this.idhallazgo;
    }
    
    public void setIdhallazgo(Integer idhallazgo) {
        this.idhallazgo = idhallazgo;
    }

    
    @Column(name="nombre", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="simbolol", length=50)
    public String getSimbolol() {
        return this.simbolol;
    }
    
    public void setSimbolol(String simbolol) {
        this.simbolol = simbolol;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="hallazgo")
    public Set<DetalleHallazgo> getDetalleHallazgos() {
        return this.detalleHallazgos;
    }
    
    public void setDetalleHallazgos(Set<DetalleHallazgo> detalleHallazgos) {
        this.detalleHallazgos = detalleHallazgos;
    }




}


