package OdontoSysModelo;
// Generated 24/07/2014 08:45:38 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrdenServicio generated by hbm2java
 */
@Entity
@Table(name="orden_servicio"
    ,catalog="odontosys"
)
public class OrdenServicio  implements java.io.Serializable {


     private Integer idordenServicio;
     private Odontograma odontograma;
     private Paciente paciente;
     private Date fecha;
     private String estado;
     private Set<Agenda> agendas = new HashSet<Agenda>(0);
     private Set<Factura> facturas = new HashSet<Factura>(0);
     private Set<DetalleOrden> detalleOrdens = new HashSet<DetalleOrden>(0);

    public OrdenServicio() {
    }

	
    public OrdenServicio(Odontograma odontograma, Paciente paciente, Date fecha, String estado) {
        this.odontograma = odontograma;
        this.paciente = paciente;
        this.fecha = fecha;
        this.estado = estado;
    }
    public OrdenServicio(Odontograma odontograma, Paciente paciente, Date fecha, String estado, Set<Agenda> agendas, Set<Factura> facturas, Set<DetalleOrden> detalleOrdens) {
       this.odontograma = odontograma;
       this.paciente = paciente;
       this.fecha = fecha;
       this.estado = estado;
       this.agendas = agendas;
       this.facturas = facturas;
       this.detalleOrdens = detalleOrdens;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idorden_servicio", unique=true, nullable=false)
    public Integer getIdordenServicio() {
        return this.idordenServicio;
    }
    
    public void setIdordenServicio(Integer idordenServicio) {
        this.idordenServicio = idordenServicio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_odontograma", nullable=false)
    public Odontograma getOdontograma() {
        return this.odontograma;
    }
    
    public void setOdontograma(Odontograma odontograma) {
        this.odontograma = odontograma;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_paciente", nullable=false)
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="estado", nullable=false, length=20)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ordenServicio")
    public Set<Agenda> getAgendas() {
        return this.agendas;
    }
    
    public void setAgendas(Set<Agenda> agendas) {
        this.agendas = agendas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ordenServicio")
    public Set<Factura> getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set<Factura> facturas) {
        this.facturas = facturas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ordenServicio")
    public Set<DetalleOrden> getDetalleOrdens() {
        return this.detalleOrdens;
    }
    
    public void setDetalleOrdens(Set<DetalleOrden> detalleOrdens) {
        this.detalleOrdens = detalleOrdens;
    }




}


