package OdontoSysModelo;
// Generated 24/07/2014 08:45:38 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Recibo generated by hbm2java
 */
@Entity
@Table(name="recibo"
    ,catalog="odontosys"
)
public class Recibo  implements java.io.Serializable {


     private Integer idrecibo;
     private Factura factura;
     private Usuario usuario;
     private Paciente paciente;
     private int monto;
     private Date fecha;
     private Set<Movimiento> movimientos = new HashSet<Movimiento>(0);
     private Set<DetalleRecibo> detalleRecibos = new HashSet<DetalleRecibo>(0);

    public Recibo() {
    }

	
    public Recibo(Factura factura, Usuario usuario, Paciente paciente, int monto, Date fecha) {
        this.factura = factura;
        this.usuario = usuario;
        this.paciente = paciente;
        this.monto = monto;
        this.fecha = fecha;
    }
    public Recibo(Factura factura, Usuario usuario, Paciente paciente, int monto, Date fecha, Set<Movimiento> movimientos, Set<DetalleRecibo> detalleRecibos) {
       this.factura = factura;
       this.usuario = usuario;
       this.paciente = paciente;
       this.monto = monto;
       this.fecha = fecha;
       this.movimientos = movimientos;
       this.detalleRecibos = detalleRecibos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idrecibo", unique=true, nullable=false)
    public Integer getIdrecibo() {
        return this.idrecibo;
    }
    
    public void setIdrecibo(Integer idrecibo) {
        this.idrecibo = idrecibo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_factura", nullable=false)
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_usuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_paciente", nullable=false)
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }

    
    @Column(name="monto", nullable=false)
    public int getMonto() {
        return this.monto;
    }
    
    public void setMonto(int monto) {
        this.monto = monto;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="recibo")
    public Set<Movimiento> getMovimientos() {
        return this.movimientos;
    }
    
    public void setMovimientos(Set<Movimiento> movimientos) {
        this.movimientos = movimientos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="recibo")
    public Set<DetalleRecibo> getDetalleRecibos() {
        return this.detalleRecibos;
    }
    
    public void setDetalleRecibos(Set<DetalleRecibo> detalleRecibos) {
        this.detalleRecibos = detalleRecibos;
    }




}


