package OdontoSysModelo;
// Generated 24/07/2014 08:45:38 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tratamiento generated by hbm2java
 */
@Entity
@Table(name="tratamiento"
    ,catalog="odontosys"
)
public class Tratamiento  implements java.io.Serializable {


     private Integer idtratamiento;
     private Odontograma odontograma;
     private Servicio servicio;
     private Diente diente;
     private String estado;
     private String especificacion;

    public Tratamiento() {
    }

    public Tratamiento(Odontograma odontograma, Servicio servicio, Diente diente, String estado, String especificacion) {
       this.odontograma = odontograma;
       this.servicio = servicio;
       this.diente = diente;
       this.estado = estado;
       this.especificacion = especificacion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idtratamiento", unique=true, nullable=false)
    public Integer getIdtratamiento() {
        return this.idtratamiento;
    }
    
    public void setIdtratamiento(Integer idtratamiento) {
        this.idtratamiento = idtratamiento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_odontograma", nullable=false)
    public Odontograma getOdontograma() {
        return this.odontograma;
    }
    
    public void setOdontograma(Odontograma odontograma) {
        this.odontograma = odontograma;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_servicio", nullable=false)
    public Servicio getServicio() {
        return this.servicio;
    }
    
    public void setServicio(Servicio servicio) {
        this.servicio = servicio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_diente", nullable=false)
    public Diente getDiente() {
        return this.diente;
    }
    
    public void setDiente(Diente diente) {
        this.diente = diente;
    }

    
    @Column(name="estado", nullable=false, length=20)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="especificacion", nullable=false)
    public String getEspecificacion() {
        return this.especificacion;
    }
    
    public void setEspecificacion(String especificacion) {
        this.especificacion = especificacion;
    }




}


